# The United States and the Soviet Union

Whatever their other commitments or capabilities, the primary mission of American armed forces remains the deterrence of a strategic attack, necessarily with nuclear weapons, upon the United States. The principal object of that deterrence is the only other 'super-power', the Soviet Union, with China as a subsidiary object of potentially increasing importance. Conversely, although less explicitly, Soviet strategic nuclear forces appear to be designed primarily to deter an American strategic attack upon the Soviet Union. The strategic forces and weapons of both super-powers have capabilities which, at least in theory, go beyond reciprocal deterrence, to the point of offering some prospect of limiting the damage which either would suffer should a strategic nuclear war occur. They also provide means of deterring lesser nuclear powers. In terms of intentions, however, it seems that deterrence of each other represents the first priority for both countries. Soviet and American representatives have been engaged since November 1969 in an effort to agree upon the mutual limitation of strategic nuclear forces. These Strategic Arms Limitation Talks (SALT) have not yet produced any formal agreement, although the governments issued a statement on 20 May 1971 in which they spoke of working out an agreement during the remaining months of the year which would limit the deployment of anti-ballistic missile (ABM) systems and which would also include 'certain measures' of limitation on offensive weapons. Meanwhile, the expansion or modernization of strategic nuclear forces has continued on both sides. The Soviet Union, having matched the American total of offensive strategic missiles, has continued to deploy addi- tional inter-continental, ballistic missiles (ICBMs) on land, to construct additional ballistic-missile submarines and to develop more effective weapons for its offensive forces. At the same time, the United States has embarked upon an extensive modernization of its strategic offensive weapons which, over the next four years, will add considerably to the number and effectiveness of the nuclear warheads which its own land-based and sea-based forces can deliver. Both countries have also pursued attempts to deploy an effective ABM system: the Soviet Union by improving the small system which it already has, the United States by starting deployment of the Safeguard system which was announced in 1969. With an estimated total of 1,510 ICBM (about 100 of which are positioned in MR/IRBM fields, and may, therefore, be intended for possible use against targets other than the United States), the Soviet Union has now surpassed the United States ICBM force of 1,054. Soviet deployment has, however, slowed down considerably since the beginning of 1970 and may have reached, or be approaching, its planned level. A number of underground silos of a new type have been observed, but it is not clear whether these are intended to fire a new ICBM (of which no other evidence has been reported) or to provide added protection for missiles of existing types, and especially for the large SS-9 missile. If, as seems possible, the latter is the case, this improvement of the silo for the SS-9 system will match the testing of an SS-9 multiple warhead cluster, containing three re-entry vehicles, in which the Soviet Union has been actively engaged since 1968. The United States has made no effort to increase its total of ICBM launchers. It has, however, continued the replacement of Minuteman 1 missiles with Minuteman 3 missiles which began in 1970. Over 500 Minuteman 3 launchers, each of which carries three independently-targeted war- heads, are to be deployed, under present plans, by 1975. This will have the effect of doubling the number of targets at which the total Minuteman force can strike. Although the Soviet Union has continued to launch Y-class ballistic-missile submarines now at a rate of some 7-8 a year, it has not yet overtaken the United States in this field. It now has about 350 SLBMs in nuclear-powered submarines (of which some 320 are in modern Y-class boats), in contrast with the 656 launchers in the parallel American force. In terms of launcher totals, the Soviet Union's construction programme continues to bring it closer to the United States at a rate which could produce numerical equality by 1974. Moreover, the Soviet Union has been testing 2 a new SLBM which, with its estimated range of some 3,000 miles, would be comparable to the American Polaris vehicle. Meanwhile, the United States has begun to deploy the more advanced Poseidon SLBM, with at least 10 independently-targeted re-entry vehicles. The first submarine equipped with Poseidon became operational during early 1971; the completion of the planned programme for converting 31 boats would raise the total number of nuclear warheads deliverable by the American SLBM force from about 1,500 (capable of attacking 656 separate targets) to over 5,400 (capable of attacking some 5,000 separate targets). For the longer term, development work continues on an Undersea Long-Range Missile System (ULMS), which might replace the Poseidon submarines themselves at the end of the 1970s. In contrast with the quantitative reinforcement of their offensive missile forces, the Soviet Union and the United States have continued to allow their strategic bomber forces to dwindle. The number of American B-52 bombers in service has dropped to well below 500, while the Soviet force of Mya-4 Bison and Tu-20 Bear bombers is now estimated at 140 aircraft (with an additional 50 Bison tankers). On the American side, however, the effectiveness of the B-52 force is likely to be greatly increased by the introduction of the new Short-Range Attack Missile (SRAM), which has been ordered into production and which is expected to have an operational range of 60-75 miles. Each B-52 could carry up to 24 SRAM, while the proposed B-1 bomber, prototype development of which is under way, would, if produced, be able to carry some 32 SRAM when it became opera- tional in about 1978. The total number of nuclear weapons deliverable by the American strategic bomber force is thus likely to rise sharply during the next five years. The Soviet Union has shown no apparent interest in matching this particular effort. The prototype of a new variable-geometry ('swing-wing') bomber has been observed, but it is not clear that, even if produced, it would have an effective inter-continental capability, and there have been no reports of any attempt to develop air-to-surface missiles for it (or for existing Soviet bombers) of a type comparable to SRAM. The Soviet Union, with some 10,000 anti-aircraft missiles (SAM) and 3,000 interceptor aircraft, has devoted a great deal more effort to territorial air defence than the United States, although the latter has continued development of its Over-the-Horizon-B (OTH-B) radar system, designed to detect attacking aircraft at great range, and of an Airborne Warning and Control System (AWACS), designed to track aircraft flying below the coverage of other radar systems. Both countries have continued to devote efforts to developing means of defence against ballistic missiles. The Soviet Union, which completed deployment around Moscow of 64 ABM launchers for its Galosh missile in 1970, has been testing an improved ABM missile and may be ready to begin its deployment. It does not appear, however, to have modified the basic orientation of its ABM system, whose missiles and radars are deployed in a manner which suggests a strong bias towards defence against an attack by American ICBM. The United States has begun work on three sites for its Safeguard ABM system, each containing long-range Spartan and short-range Sprint missiles for the protection of a part of the Minuteman force against ICBM or SLBM attack, the first of which could be opera- tional at the end of 1974. Funds have also been requested for a fourth site, either at an additional Minuteman field or at Washington, D.C., as well as for the continuation of development work on an alternative system, known as Hard Site,\* for the more economical and less vulnerable defence of Minuteman. On both sides, however, continued deployment of ABM launchers now depends heavily upon the outcome of the SALT negotiations. The manpower strength of American conventional forces has declined from the 1968 peak of over 3.5 million to the 'pre-Vietnam' level of 2.7 million and is well on the way towards the 1972 target of 2.5 million. At the same time, withdrawals from Vietnam and South Korea and the re- deployment of units from Japan have marked the further contraction of American military deploy- ment in Asia. No parallel manpower reductions or deployment changes have been apparent in the Soviet case. As far as navies are concerned the American tendency to reduce the active ship strength, while improving its quality, has been generally followed by the Soviet Union. Both navies have reduced overall numbers while continuing with modernization (see p. 82 for some comparative figures of new construction). This would replace the Safeguard Missile Site Radars (MSR) with a large number of smaller and cheaper radars. 

## THE UNITED STATES 

Population: 208,100,000. 

Military service: selective service for two years.

Total armed forces: 2,699,000. 

Estimated GNP 1970: \$977 billion. 

Defence budget 1971-72: \$78,743 million.

### Strategic Forces

### (A) OFFENSIVE

ICBM: 1,054 (Strategic Air Command - SAC). 400 Minuteman 1. 500 Minuteman 2. 100 Minuteman. 54 Titan 2. 

SLBM: (US Navy) 656 in 41 SSBN: 4 with Poseidon (4 more are converting). 27 with Polaris A-3. 10 with Polaris A-2. 

Aircraft (SAC) Bombers: 520 70 FB-111 in 4 squadrons. 150 B-52 C/F in 10 squadrons. 210 B-52 G/H in 14 squadrons. 90 B-52 in active storage. 

Tankers: 420 KC-135. 

Strategic Reconnaissance: SR-71; 2 squadrons. 

### (B) DEFENSIVE 

North American Air Defense Command (NORAD), with its headquarters at Colorado Springs, is a joint Canadian-American organization. Ameri- can forces under NORAD are Aerospace Defense Command (ADC) and Army Defense Command (ARADCOM); combined strength 80,000. 

Aircraft

Interceptors: 522. 

(i) regular: 11 squadrons with F-106. 

(ii) National Guard: 5 squadrons with F-101; 12 squadrons with F-102; 1 squadron with F-104. 

AEW aircraft: 3 squadrons with EC-121. 

SAM (i) regular: 2 battalions with HAWK; 5 squadrons with 170 Bonmarc B. A reform of the selective service system is being worked on. 

1 July 1973 has been set as the target date for reaching zero draft calls. t 

New obligational authority for FY 1971-72; expected outlay is \$76,000 million. + Characteristics of missiles and aircraft are given in Table 2 on p. 57. ยง 2 squadrons of B-52, and about 100 KC-135 are based in South-East Asia. II Excluding Canadian. 

(ii) National Guard: 27 batteries with Nike- Hercules. Radar and tracking stations - a chain including: the Ballistic Missile Early Warning System (BMEWS),- with stations in Alaska, Greenland and England. the 'forward scatter' Over-the-Horizon radar- system." the Pinetree line. the 33 radar Distant Early Warning Line (DEW). Surveillance and tracking of objects in North American air space is co-ordinated by the Semi- Automatic Ground Environment (SAGE) Sys- tem. Fourteen locations are combined with Back-Up Interceptor Control (BUIC) stations. A system (474N) of seven radar stations on the East, West and Gulf Coasts of the United States is designed specifically for the detection of submarine-launched missiles. 

### Army: 1,107,000.

3 armoured divisions. 1 cavalry division. 4 infantry divisions (mechanized) 2 infantry divisions 2 airborne divisions. 1 cavalry brigade. 3 independent infantry brigades. 1 airborne brigade. 5 armoured cavalry regiments. 5 special forces groups. 30 SSM batteries. About 200 independent aviation units with 11,600 aircraft, incl 9,000 helicopters. M-48 and M-60 med tanks; M-60 AIE2 med and M-551 Sheridan It tanks with Shillelagh; M-107 175mm SP guns, M-109 155mm and M-110 203mm SP howitzers; Honest John, Sergeant and Pershing SSM; HAWK and Nike-Hercules SAM; the Chaparral\| Vulcan air defence system; and the TOW ATGW system. 

#### RESERVES:

(i) Army National Guard: 400,000 men capable, in five weeks from mobilization, of providing 8 full divisions and some smaller units to round out regular formations, and 36 SAM batteries with Nike-Hercules.

(ii) Army Reserves: average paid training strength 260,000, organized in 21 brigades. In addition 48,000 undergo short tours of active duty. IT This radar-system can detect ICBM regardless of the direction or trajectory of their launch. 

### Marine Corps: 212,000.

3 divisions (19,000 men), each supported by: 1 tank battalion and 1 SAM battalion with 24 HAWK. M-48 and M-103 tanks; 105mm SP howitzers; 105mm and 155mm howitzers; 175mm guns. 3 Air Wings; 540 combat aircraft. 14 fighter squadrons with F-4 (with Sparrow and Sidewinder AAM). 12 attack squadrons, with A-6A and A-4. 1 close-support squadron with AV-8A Harrier. 3 recce squadrons with RF-4B and RF-8A. 45 AH-1 Cobra gunship helicopters. 6 heavy helicopter squadrons with CH-53A. 9 medium helicopter squadrons with CH-46A. 3 assault transport squadrons with C-130. RESERVES: Average paid training strength 49,500, plus paid training tours for a further 560. They form a reserve division and an associated air wing, which includes 4 squadrons with F-8, 5 squadrons with A-4, 2 squadrons with CH-53 and 3 squadrons with CH-46. 

### DEPLOYMENT:

Ground forces, Army and Marines, were deployed as -follows at the beginning of July 1971:

(i) Strategic Reserve - 1 armd div; 1 cav div; 1 airborne div; 1 mech inf div; 2 marine divs; 1 marine bde; 1 armd cav regt.

(ii) To reinforce 7th Army in Europe - 1 mech inf div (less 1 bde)\* 1 armd cav regt; 1 Special Forces gp.

(iii) Other - 1 inf bde; 1 airborne bde; 1 armd cav regt; 2 Special Forces gps. Hawaii - 1 inf bde; 1 marine div (less 1 bde). Germany

(iv) 7th Army - two Corps incl: 2 armd divs; 2 armd cav regts; 2 infantry divs (mech); 1 infantry bde (mech).

(v) West Berlin: 1 infantry bde. Italy - Task Force with HQ elements and 1 SSM bn. South Vietnam - 1 inf div; 1 airborne div; 1 cav bde; 1 mech bde. South Korea - 1 infantry div. Okinawa - 1 Special Forces gp. Continental United States Navy: 623,000 Aircraft carriers Submarines, attack: 53 nuclear-powered (40 with Subroc), and 46 diesel-powered.

(vi) Anti-submarine: 3. Essex-class, each with 52 aircraft and helicopters, incl A-4C for air defence, S-2E for long-range search and SH-3 helicopters.

(vii) Attack: 15. 1 nuclear-powered (USS Enterprise, 76,000 tons), 8 Forrestal-and Kitty Hawk-class (60,000 tons), 3 Midway-class (52,000 tons) and 3 Hancock-class (33,000) tons. Each normally carries an air wing of 70-85 aircraft organized in: 2 fighter sqns with F-4 (F-8 in the Hancock- class); 2 light attack sqns; 1 AWX sqn with A-6; and AEW, tanker and reconnaissance aircraft. Light attack aircraft include A-4 and A-7 (the A-7 due eventually to replace the A-4). RA-5C are used for reconnaissance (RF-8G in the Han- cock-class). E-2A and E-1B are used for AEW, and a few KA-3B as tankers. This division is dual-based and its heavy equipment is stored in West Germany. t Figures for manpower include SSBN force (see p. 3). 

### Other surface ships:

1 nuclear-powered guided-missile cruiser. 3 guided-missile cruisers. 4 guided-missile light cruisers. 1 gun cruiser. 2 nuclear-powered guided-missile frigates. 28 guided-missile frigates. 29 guided-missile destroyers. 92 gun/ASW destroyers. 6 guided-missile destroyer escorts. 51 destroyer escorts, 4 radar-picket escorts. (Guided missiles in service are Tartar, Talos and Terrier SAM and Asroc and Subroc ASW). 81 amphibious warfare ships, incl 7 LPH. 52 landing craft. 42 ocean minesweepers. 178 logistics, operational support and small patrol ships. 

### Shore-based aircraft 

24 maritime patrol sqns with 216 P-3. Transports include C-47, C-54, C-118, C-119, C-130 and C-131. 

## DEPLOYMENT: 

Fleets: 1st (Eastern Pacific), 2nd (Atlantic), 6th (Mediterranean), 7th (Western Pacific). RESERVES: Average paid training strength 127,000 plus paid training tours for a further 3,500. Training Fleet: 16 submarines. 30 destroyers. 6 ocean minesweepers. 13 coastal minesweepers. 35 squadrons of fixed-wing aircraft incl A-4 and A-7 fighters; P-2 and P-3A maritime patrol aircraft and 4 helicopter squadrons. 5 Air Force: 757,000; 6,000 combat aircraft.\* The General Purpose Forces include:

(i) Tactical Air Command: 110,000; about 1,000 aircraft normally based in the United States. 23 F-4, 4 F-105, 1 A-7D and 4 F-111 fighter squadrons. 9 tactical reconnaissance squadrons with RF-4C. 16 assault air-lift squadrons with C-130E. 4 STOL air-lift squadrons with C-7 and C-123. 2 electronic warfare squadrons. 7 special operations sqns with A-37, AC-119, C-123K and AC-130.

(ii) US Air Force Europe (USAFE): 50,000, con- trolling 3rd Air Force (Britain), 16th Air Force (Spain), 17th Air Force (West Germany), and a Logistics Group in Turkey. 21 fighter squadrons (and 4 in USA on call to USAFE) with 5F-100,F-4C/D/EandF-111E 5 tactical reconnaissance squadrons with 85 RF-4C. 2 transport squadrons with C-130.

(iii) Pacific Air Forces (PACAF): 120,000, con- trolling: 5th Air Force: over 25,000 (bases in Japan, Korea and Okinawa) with F-4, RF-4C and C-130. 13th Air Force: about 32,000 (responsible for the Philippines, Taiwan and Thailand, and all joint planning under SEATO), with F-4, F-105,

RF-4C and C-130 (of which 160 F-4, a few F-105 and 40 RF-4 fly from Thailand). 7th Air Force: 33,500 (the air component of the Military Assistance Command Vietnam, co- ordinating the operations of the Vietnamese Air Force). 200 F-4C and A-37 fighter-bombers. 40 RF-4 reconnaissance aircraft. 150 A-1E, A-37A, AC-119, AC-130 and C-123 counter-insurgency aircraft. 75 C-7A assault airlift aircraft. A large number of observation and liaison air- craft, and helicopters. (iv) Military Airlift Command (MAC): 90,000. 18 heavy transport squadrons with 35 C-133, 260 C-141 and 25 C-5A. 24 medical tpt, weather recce and SAR sqns. 

RESERVES: (i) Air National Guard: 89,000; 1,500 aircraft in 16 fighter-interceptor, 28 tactical fighter and attack, 11 tactical reconnaissance, 3 tactical air support, 4 special operations, 7 tanker and 22 air transport squadrons. (ii) Air Force Reserve: average paid training strength of 48,400 plus training tours for a further 2,600; 400 aircraft in 36 squadrons incl 2 C-119, 13 C-124 and 18 C-130 tpt sqns (the others have tactical support, special operations and SAR roles). 

## THE SOVIET UNION 

Population: 245,700,000. 

Military service: Army and Air Force, 2 years; Navy and Border Guards, 3 years. 

Total armed forces: 3,375,000. 

Estimated GNP 1970: \$490 billion.t 

Defence budget 1971: 17,854 million roublest (\$39.7 billion). 0.40-0.50 roubles= \$1.+ 

## Strategic Forces 

(A) OFFENSIVE (Strategic Rocket Forces (SRF) - 350,000)ll \* Figures for manpower include strategic air forces. t An explanation of the valuation of GNP was given in The Military Balance 1970-1971, pp. 10-12, together with a note on the exchange rate used for military expenditure. For another, much discussed, view on this exchange rate see The Technological Base of Soviet Military Power, by Michael Boretsky, a Paper sub- mitted in September 1970 to the Subcommittee on Foreign Economic Policy of the US Congressional Joint Economic Committee. See Survival, October 1971. The official exchange rate is 0.9 roubles ICBM: about 1,510. 220 SS-7 and SS-8. 280 SS-9. 950 SS-11 (about 100 have been sited in IRBM/ MRBM fields and may have a variable range capability). 60 SS-13 (solid-fuelled). IRBM and MRBM: about 700. 100 SS-5 IRBM. 600 SS-4 MRBM.

The rouble figure represents the declared budget of the Ministry of Defence and does not include certain expenditures such as the cost of nuclear warheads, research and development expenditure on advanced weapons systems, and the military elements of the space programme, which are believed to be included in the budget of other ministries. Total military ex- penditure could be of the order of \$55 billion. ยง Characteristics of nuclear delivery vehicles are given in Table 1 on p. 55. II The Strategic Rocket Forces are a separate Service, with their own manpower. 6 (IRBMs and MRBMs are sited near the southern, eastern and western borders of the USSR: about 70 cover targets in China and Japan; and about 630 targets in Western Europe.) SLBM: 440 in 61 submarines (Navy). 20 SSBN each with 16 SS-N-6 missiles. 10 SSBN and 16 diesel each with 3 SS-N-5 missiles. 12 diesel each with 3 SS-N-4 missiles. 3 diesel each with 2 SS-N-4 missiles. Aircraft (Long Range Air Force\*). Long-range Bombers: 140. 100 Tu-20 Bear and 40 Mya-4 Bison. Tankers: 50 Bison. Medium Bombers: 700. 500 Tu-16 Badger and 200 Tu-22 Blinder. 

(B) DEFENSIVE Air Defence Command (PVO-Strany) is a separate command of anti-aircraft artillery and surface- to-air missile units, using an early-warning system based on radar, and fighter-interceptor squadrons for identification and interception; total strength 500,000 (250,000 from Army and 250,000 from Air Force). Aircraft: about 3,200. Interceptors: mostly MiG-19, MiG-21 and Su-9 with a few MiG-17 still in service. Newer aircraft include the Yak-28P and Tu-28, and more recently, the Su-11 and MiG-23. Many of these aircraft carry AAM. 

### Anti-Ballistic Missiles (ABM) 

AEW aircraft: some modified Tu-114 with the designation Moss. About 75 per cent is based on European USSR, with most of the remainder in the Far East; in addition, it has staging and dispersal points in the Arctic. Galosh: 64 launchers for these multi-stage missiles are deployed around Moscow. They are believed to have a range of over 200 miles and to carry a nuclear warhead in the megaton range. 

SA-1: An early vintage AA missile. SA-2: about 8,000. A 2-stage boosted AA missile, slant range (from launch to contact with target) about 25 miles, effective between 3,000 and 80,000 ft. SA-3: A 2-stage missile, probably intended for short-range defence against low-flying aircraft, to supplement SA-2. It has a slant range of about 15 miles. 

SA-4: An air-transportable, mobile AA missile with solid-fuel boosters. They are twin mounted on tracked carriers and assigned to ground forces in the field. 

SAM SA-5: A 2-stage boosted missile developed in a long-range AA role. 

SA-6: A triple-mounted missile on a tracked vehicle. It is entering service as a defence against low-flying aircraft to supplement SA-4 in the field forces. 

### Army: 2,000,000 (including elements in the Air Defence Command).

102 motorized rifle divisions. 51 tank divisions. 7 airborne divisions. Tactical nuclear missile units are organic to forma- tions. T-10 hy tanks; T-62 and T-54/-55 med tanks; PT-76 amphibious recce It tanks (most Soviet tanks are equipped for amphibious crossing by deep wading, and many carry infra-red night- fighting equipment). At full strength, tank divisions have 325 medium tanks and motorized rifle divisions 175. SP assault guns (in AB divs only); 100mm, 122mm, 130mm, 152mm and 203mm guns; 57mm, 85mm, 100mm, 120mm and 130mm ATk guns; Scud Scaleboard FROG SSM, mounted on modified tank chassis and wheeled launchers; Shaddock cruise SSM; Snapper, Swatter and Sagger ATGW. The Soviet Army also has a considerable air defence capability, including SAM. Anti-Aircraft Artillery 14.5mm, 23mm, 57mm guns and ZSU-57-2 twin- barrelled and ZSU-23-4 four-barrelled SP guns on tank chassis. Central and Eastern Europe: 31 divs of which 20 divs (10 tank) are in East Germany; 2 tank divs in Poland; 4 divs (2 tank) in Hungary; and 5 divs in Czechoslovakia. Central USSR (between the Ural Mountains and Lake Baikal): 8 divs. Southern USSR (Caucasus and West Turkestan): 28 divs. Sino-Soviet border area: 33 divs (10 tank) incl 2 divs in Mongolia. The 31 divisions in Eastern Europe are maintained at or near combat-strength, as are about 15 of those in the Far East. The other divisions in the Far East are probably in the second category of readiness: below combat-strength, but not requiring major reinforcement in the event of war. Most of the remaining combat-ready divisions are in European USSR, while the divisions in central USSR would mostly require major reinforcement, as would 10 of the divisions in southern USSR. 

### DEPLOYMENT: 

European USSR: 60 divs. 7 Outside the Warsaw Pact area (mostly as instruc- tors and advisors). 1,000 in Cuba, 15-20,000 in Egypt, 1,000 in Sudan, 1,000 in Syria, 1,500 in Algeria and 1,000 in North Vietnam. Navy: 475,000 (incl Naval Air Force 75,000). Submarines (excluding ballistic-missile vessels): Attack: 25 nuclear-powered; 210 diesel-powered. Cruise-missile: 35 nuclear-powered and 25 diesel- powered (with 4-8 300-mile range msls). 

### Surface ships

2 ASW helicopter cruisers with SAM and up to 20 KA-25 helicopters. 2 Kresta II-class cruisers with (horizon-range) surface-to-surface cruise missiles (SSCM) and SAM. 4 Kresta I-class cruisers with SSCM and SAM. 4 Kynda-class cruisers with SSCM and SAM. 8 Sverdlov-class and 2 older cruisers (1 with SAM). 1 Krivak-class destroyer with SSCM and SAM. 6 Kanin-class destroyers with SAM. 3 Krupny-class destroyers with SSCM. 4 Kildin-class destroyers with SSCM. 17 Kashin-class destroyers with SAM. 9 modified Kotlin-class destroyers with SAM. 23 Kotlin-class destroyers. 40 Skory- and modified Skory-class destroyers. 105 other ocean-going escorts. 250 coastal escorts and submarine chasers. 110 Osa- and 30 Komar-class patrol boats with SSCM. 250 fast patrol boats. 180 fleet minesweepers. 125 coastal minesweepers. 105 landing ships and numerous landing craft. Some trawlers are used for electronic intelligence. All submarines and the larger surface vessels not fitted with SSM are equipped for minelaying. A proportion of the destroyers and smaller vessels may not be fully manned. Shore-based aircraft Bombers: 500, most based near the north-west and Black Sea coasts of the USSR. 300 Tu-16 with Kipper or Kelt ASM. 100 Tu-16 reconnaissance and tanker aircraft (replacement of the reconnaissance version with the Tu-22 Blinder has begun). 50 II-28 torpedo-equipped light bombers. 50 Tu-20 long-range naval reconnaissance. Other aircraft and helicopters - 500. 75 Be-12 ASW amphibians. 25 Il-18 May ASW aircraft. 200 Mi-4 and Ka-25 ASW helicopters. 200 miscellaneous transports. Naval Infantry - about 15,000. DEPLOYMENT: Arctic, Baltic, Black Sea and Far East Fleets. 

### Air Force: 550,000: 10,000 combat aircraft.

(i) The Long Range Air Force (see p. 6).

(ii) Tactical Air Force: altogether about 5,000 aircraft, incl light bombers, fighters, helicopters, transport and reconnaissance aircraft. Some obsolescent MiG-17, MiG-19 and Il-28 are still in service. The most notable high performance aircraft are the MiG-21J and Yak-28P Firebar fighters; the ground-attack Su-7; and the super- sonic light bomber Yak-28. Ground-attack air- craft are equipped with a variety of air-to-ground rockets. The variable-geometry Flogger may be about to enter service.

(iii) Air Defence Command (see p. 6), and (iv) Naval Air Force (see above).

(iv) Air Transport Force - about 1,700 aircraft. Il-14, An-24, some 800 An-12 and Il-18 medium transports and 10 An-22 heavy transports. There are in addition civil airliners of Aeroflot, some of which could be adapted to military use; these include about 275 long- and medium-range Tu-104, Tu-114, Tu-124 and Tu-134. About 800 helicopters in use with the ground forces including troop-carrying Mi-6 and Mi-8 and the heavy load-carrier Mi-10. The Mi-12, a very heavy load carrier, may soon enter service. The total helicopter inventory is probably around 1,750. Para-Military Forces: 300,000. 125,000 security troops; 175,000 border troops. There are also about 1.5 million members of the part-time military training organization (DOSAAF), who take part in such recreational activities as athletics, shooting and parachuting, but reservist training and refresher courses seem to be haphazard and irregular. However, DOSAAF assists in pre-military training being given in schools, colleges, and workers' centres, to those of 16 years and over.
