# The European Balance

## THE WARSAW PACT 

Treaties The Warsaw Pact is a multilateral military alliance formed by a 'Treaty of Friendship, Mutual Assistance and Co-operation', which was signed in Warsaw on 14 May 1955 by the Governments of the Soviet Union, Albania, Bulgaria, Czechoslovakia, East Germany, Hungary, Poland and Rumania. (Albania denounced the Pact in September 1968.) According to East European docu- mentary sources the Pact is committed to the defence of only the European territories of the member states. The Soviet Union is also linked by bilateral treaties of friendship and mutual assistance with Bulgaria, Czechoslovakia, East Germany, Hungary, Poland, and Rumania. All present members of the Warsaw Pact also have similar bilateral treaties with each other. The Soviet Union con- cluded status-of-forces agreements with Poland, East Germany, Rumania and Hungary between December 1956 and May 1957 and with Czechoslovakia in October 1968; all these remain in effect except the one with Rumania which lapsed in June 1958 when Soviet troops left Rumania. The essence of East European defence arrangements is not therefore dependent on the Warsaw Treaty as such. 

### Organization 

The Organization of the Warsaw Pact has two main bodies. The first, the Political Consultative Committee, consists, in full session, of the First Secretaries of the Communist Party, Heads of Government and the Foreign and Defence Ministers of the member-countries. It met twice in the year up to July 1971, at which point there had been 17 meetings in all\*. The Committee has a Joint Secretariat, headed by a Soviet officer, consisting of a specially appointed official from each country, and a Permanent Commission, whose task is to make recommendations on general questions of foreign policy for Pact members. Both these bodies are located in Moscow. The second body, the Joint High Command, is directed, according to the Treaty, 'to strengthen the defensive capability of the Warsaw Pact, to prepare military plans in case of war and to decide on the deployment of troops'. The Command consists of a Commander-in-Chief (C-in-C), a Defence Committee, made up of the six Defence Ministers of the Pact, which acts as an advisory body, and a Military Council. This body, which is modelled on a similar organization in the Soviet Armed Forces, meets under the chairmanship of the C-in-C, and includes the Chief of Staff (C of S) and permanent military representatives from each of the allied armed forces. (It seems to be the main channel through which the Pact's orders are transmitted to its forces in peacetime, and through which the East European forces are able to put their point of view to the C-in-C.) The Pact also has a Military Staff, which has been enlarged by additional non-Soviet senior officers. The posts of C-in-C and C of S of the Joint High Command have, however, always been held by Soviet officers, and most of the key positions are still in Soviet hands. In the event of war, the forces of the other Pact members would be operationally subordinate to the Soviet High Command. The command of the air defence system covering the whole Warsaw Pact area is centralized in Moscow and directed by the C-in-C of the Soviet Air Defence Forces. The Soviet forces in the Warsaw Pact area are organized as the Northern Group of Forces, with headquarters at Legnica in Poland; the Southern Group of Forces, with headquarters at Budapest; Some of these meetings have been entitled Meetings of Ministers. 9 the Group of Soviet Forces in Germany, with headquarters at Zossen-Wünsdorf, near Berlin; and the Central Group of Forces, consisting of five divisions in Czechoslovakia, with headquarters at Milovice, north of Prague. Soviet tactical air forces are stationed in Poland, East Germany, Hungary and Czechoslovakia. The Soviet Union has deployed tactical nuclear missiles in Eastern Europe. Most East European countries have displayed short-range SSM launchers, but there is no evidence that nuclear warheads for these missiles have been supplied to these countries. Soviet MRBM (and other strategic weapons) are based in the Soviet Union and remain under Soviet control. 

## BULGARIA 

Population: 8,555,000. 

Military service: Army and Air Force, 2 years; Navy, 3 years. 

Total regular forces: 148,000. 

Estimated GNP 1970: \$8.9 billion. 

Defence expenditure 1970: 324 million leva (\$279,000,000). 1.16 leva = \$1. 

### Army: 117,000. 

8 motorized rifle divisions (3 cadre). 5 tank brigades. 30 JS-3 and T-10 hy tanks; about 1,900 med tanks, mainly T-54, with some T-34, T-55 and T-62; PT-76 It tanks, and BTR-40P scout cars; BTR-50, BTR-60 and BTR-152 APC; over 500 85mm, 122mm, 130mm, and 152mm guns; SU-100 and JSU-122mm SP guns; FROG and Scud SSM; 57mm, 85mm and 100mm ATK guns; Snapper, Swatter and Sagger ATGW; ZSU-57 SP AA guns; SA-2 SAM. 

### Navy: 9,000.

2 submarines. 2 escorts. 8 coastal escorts. 2 minesweepers. 2 minehunters. 4 inshore minesweepers. 12 motor torpedo boats (8 less than 100 tons). 14 landing craft. A small Danube flotilla. 

### Air Force: 22,000; 252 combat aircraft.

6 fighter-bomber squadrons with MiG-17. 4 interceptor squadrons with MiG-21. 3 interceptor squadrons with MiG-19. 5 interceptor squadrons with MiG-17. 1 reconnaissance squadron with II-28. (12 aircraft in a combat squadron.) 2 reconnaissance squadrons with MiG-17C. 4 Li-2, 6 An-2 and 10 Il-14 transports. About 40 Mi-4 helicopters. 1 parachute regiment. Para-Military Forces: 15,000 including border security troops. A volunteer People's Militia of 150,000. 

## CZECHOSLOVAKIA 

Population: 14,700,000. 

Military service: Army 24 months; Air Force 27 months. 

Total regular forces: 185,000. 

Estimated GNP 1970: \$30.3 billion. 

Defence expenditure 1970: 15,000 million crowns (\$1,765,000,000). 8.5 crowns = \$1. 

### Army: 145,000. 

4 tank divisions. 8 motorized rifle divisions. 1 airborne brigade. (All about 70 per cent of strength except 2 cadre motorized rifle divisions at 30 per cent strength.) About 100 JS-3 and T-10 hy tanks: about 3,400 med tanks, mostly T-55 and T-62, with some T-54 and T-34; OT-65 and FUG-1966 scout cars; BTR-50P, BTR-152, OT-62 and OT-64 APC; SU-100, SU-122, JSU-152 SP guns; 82mm and 120mm mortars; FROG and Scud SSM; 57mm, 85mm and 100mm ATk guns; Snapper, Swatter and Sagger ATGW; 47mm twin SP and 30mm AA guns; SA-2 SAM, 

### Air Force: 40,000; 504 combat aircraft.

12 ground-support squadrons with II-28, Su-7, MiG-15 and MiG-17. 18 interceptor squadrons with MiG-17, MiG-19 and MiG-21. 6 reconnaissance squadrons with MiG-15 and L-29 (14 aircraft in a combat squadron.) About 50 Li-2, Il-14 and Il-18 transports. About 90 Mi-1, Mi-4 and Mi-8 helicopters. Para-Military Forces: Border troops (Pohranicki straz) - 35,000. A part-time People's Militia of about 120,000 is being increased to 250,000. 10 \# 

## GERMAN DEMOCRATIC REPUBLIC 

Population: 17,150,000. 

Military service: 18 months. 

Total regular forces: 126,000. 

Estimated GNP 1970: \$34 billion. 

Defence budget 1971: 7,200 million Ostmarks (\$2,124,000,000). 3.39 Ostmarks = \$1. 

### Army: 90,000. 

2 tank divisions. 4 motorized rifle divisions. About 100 T-10 and JS-3 hy tanks; about 2,200 med tanks, mostly T-54 and T-55, with some T-34 and T-62; about 125 PT-76 It tanks; SK-1 armd cars; BTR-40P scout cars; about 650 BTR-50P, BTR-60P and BTR-152 APC; SU-100 SP guns; 85mm, 122mm, 130mm and 152mm guns; FROG and Scud SSM: 57mm and 100mm ATk guns; Snapper, Swatter and Sagger ATGW; ZSU-57-2 SP, 57mm and 100mm AA guns. 

### Navy: 16,000. 

4 destroyer escorts. 25 coastal escorts. 47 minesweepers. 12 Osa-class patrol boats with Styx SSM. 70 motor torpedo boats (less than 100 tons). 18 landing craft. 16 Mi-4 helicopters. 

### Air Force: 20,000; 

290 combat aircraft. 2 interceptor squadrons with MiG-17. 16 interceptor squadrons with MiG-21. (16 aircraft in a combat squadron.) 30 transports, including An-2, Il-14 and Li-2. 20 Mi-1, Mi-4 and Mi-8 helicopters. An anti-aircraft division of 9,000 (5 regiments), with about 120 57mm and 100mm AA guns and with SA-2 SAM. Para-Military Forces: 46,000 border troops (Grenz- schutztruppe) including a Border Command separate from the regular army. 20,000 security troops. 350,000 in armed workers' organizations (Betriebskampfgruppen). 

## HUNGARY 

Population: 10,320,000. 

Military service: 2-3 years. 

Total regular forces: 103,000. 

Estimated GNP 1970: \$14.4 billion. 

Defence expenditure 1970: 8,900 million forints (\$511,000,000). 17.4 forints = \$1.

### Army: 90,000. 

2 tank divisions. 5 motorized rifle divisions. 2 SAM battalions with SA-2. T-10 hy tanks; about 1600 med tanks, mainly T-55, with some T-34, T-54 and T-62; 50 PT-76 It tanks; FUG-A armd cars; OT-65 scout cars; OT-64, OT-66 and BTR-152 APC; SU-100 and JSU-122 SP guns; about 400 76mm, 85mm and 122mm guns, and 122mm howitzers; FROG SSM; 57mm ATk guns; Snapper, Swatter and Sagger ATGW; ZSU-57 SP AA guns; SA-2 SAM. 

#### Navy: 500. 

There is a Danube flotilla of: 40 minesweepers. 20 patrol craft. 

### Air Force: 12,500; 130 combat aircraft. 

1 fighter-bomber/recce squadron with MiG-17. 10 interceptor squadrons with MiG-19 and MiG-21. (12 aircraft in a combat squadron.) About 25 An-2, Il-14 and Li-2 transport aircraft. About 6 Mi-1 and Mi-4 helicopters. 

### Para-Military Forces: 27,000 security and border guard troops. 

250,000 workers' militia. 

## POLAND Population: 33,200,000. 

Military service: Army and Air Force, 2 years; Navy and special services, 3 years; Internal security forces, 27 months. 

Total regular forces: 265,000. 

Estimated GNP 1970: \$42.5 billion. 

Defence expenditure 1970: 35,300 million zloty (\$2,220,000,000). 15.9 zloty=\$1. 

### Army: 190,000. 

5 tank divisions. 8 motorized rifle divisions. 1 airborne division. 1 amphibious assault division. (Divisions are at 70 per cent of strength, except those in the Warsaw Military District which are at 30-50 per cent of strength.) 30 JS-3 and T-10 hy tanks; 3,400 med tanks, mostly T-54 and T-55, with some T-34 and T-62; about 150 PT-76 It tanks; FUG-A armd cars; BTR-40P scout cars; OT-62, OT-64 (Skot-2) and BTR M-1967 APC; ASU-57, SU-100, JSU-122 and JSU-152 SP g7ns; FROG and Scud SSM; 57mm, 85mm and 100mm anti- tank guns; Snapper, Swatter and Sagger ATGW; SA-2 SAM. 

### Navy: 20,000 (including 1,000 marines).

5 submarines. 2 destroyers. 30 coastal escorts/submarine chasers. 24 fleet minesweepers. 27 inshore minesweepers. 12 Osa-class patrol boats with Styx SSM. 20 torpedo boats (less than 100 tons). 22 landing ships. 45 naval aircraft, mostly MiG-17, with a few Il-28 It bombers, and some helicopters. Samlet cruise missiles for coastal defence. 

### Air Force: 55,000; 730 combat aircraft.

6 light bomber/recce squadrons with Il-28.

12 fighter-bomber squadrons with MiG-17 and Su-7. 40 interceptor squadrons with MiG-17, MiG-19 and MiG-21. 3 reconnaissance squadrons with MiG-15 and MiG-17. (12 aircraft in a combat squadron.) About 45 An-2, An-12, Il-12, II-14, Il-18 and Li-2 transports. 40 helicopters, including Mi-1 and Mi-4. Para-Military Forces: 65,000 security and border troops, including armoured brigades of the Frontier Defence Force, and operating 20 small patrol boats. 
## ROMANIA Population: 20,400,000. 

Military service: Army and Air Force, 16 months; Navy, 2 years. Total regular forces: 160,000. Estimated GNP 1970: \$21.4 billion. Defence Budget 1971: 7,500 million lei (\$798,000,000). 9.4 lei=\$1. Army: 130,000. 2 tank divisions. 7 motorized rifle divisions. 1 mountain brigade. 1 airborne regiment. (All at about 90 per cent of strength.) A few JS-3 and T-10 hy tanks; 1,700 T-34, T-54, T-55 and T-62 med tanks; about 900 BTR-40, BTR-50P and BTR-152 APC; SU-100 and JSU-122 SP guns; 76mm, 122mm and 152mm guns; about 75 FROG SSM; 57mm, 85mm and 100mm ATK guns; Snapper, Swatter and Sagger ATGW; 37mm, 57mm and 100mm AA guns; SA-2 SAM.

Navy: 9,000. 6 coastal escorts. 4 minesweepers. 22 inshore minesweepers. 5 Osa-class patrol boats with Styx SSM. 12 motor torpedo boats (less than 100 tons). 8 landing craft. Air Force: 21,000; 230 combat aircraft. 18 interceptor squadrons with MiG-17, MiG-19 and MiG-21. 1 reconnaissance squadron with II-28. (12 aircraft in a combat squadron.) 1 transport squadron with II-14 and Li-2. 10 Mi-4 helicopters. Para-Military Forces: 40,000, including border troops. A militia of about 500,000. 

## THE NORTH ATLANTIC TREATY 

### Treaties 

The North Atlantic Treaty was signed in 1949 by Belgium, Britain, Canada, Denmark, France, Iceland, Italy, Luxembourg, the Netherlands, Norway, Portugal and the United States; Greece and Turkey joined in 1952 and West Germany in 1955. The Treaty unites Western Europe and North America in a commitment to consult together if the security of any one member is threatened, and to consider an armed attack against one as an attack against all, to be met by such action as each of them deems necessary, 'including the use of armed force, to restore and maintain the security of the North Atlantic area'. 12 The Paris Agreements of 1954, added a Protocol to the Treaty, strengthening the structure of NATO, and revised the Brussels Treaty of 1948, which now includes Italy and West Germany in addition to its original members (Benelux countries, Britain and France). The Brussels Treaty signatories are committed to give one another 'all the military and other aid and assistance in their power' if they are the subject of 'armed aggression in Europe'. Since 1969 members of the Atlantic Alliance can withdraw on one year's notice; the Brussels Treaty was signed for 50 years. 

### Organization 

The Organization of the North Atlantic Treaty is known as NATO. The governing body of the alliance, the North Atlantic Council, which has its headquarters in Brussels, consists of the Ministers of the fifteen member-countries, who normally meet twice a year, and, in permanent session, of ambassadors representing each government. In 1966, France left the integrated military organization and the 14-nation Defence Planning Committee (DPC), on which France does not sit, was formed. It meets at the same levels as the Council and deals with questions related to NATO's integrated military planning and other matters in which France does not participate. The Secretary-General and an international staff advise on the politico-military, financial, economic and scientific aspects of defence planning. Two permanent bodies for nuclear planning were established in 1966. The first, the Nuclear Defence Affairs Committee (NDAC) is open to all NATO members (France, Iceland and Luxem- bourg do not take part): it normally meets at Defence Minister level once or twice a year, to associate non-nuclear members in the nuclear affairs of the alliance. The Secretary-General is Chairman of the NDAC. The second, the Nuclear Planning Group (NPG), derived from and subordinate to the NDAC, has eight members, and is intended to go further into the details of topics raised there. The members in June 1971 were Britain, Canada, Germany, Italy, the Netherlands, Norway, Turkey and the United States (Belgium, Denmark and Greece had participated earlier). The Secretary-General also chairs the NPG. The Council's military advisors are the Military Committee, which gives policy direction to the NATO military commands. The Military Committee consists of the Chiefs of Staff of all member countries, except France, which maintains a liaison staff, and Iceland, which is not represented; in permanent session, the Chiefs of Staff are represented by Military Representatives who are located in Brussels together with the Council. The Military Committee has an independent Chair- man and is served by an integrated, international military staff. The major NATO Commanders are responsible to the Military Committee, although they also have direct access to the Council and heads of Governments. The principal military commands of NATO are Allied Command Europe (ACE), Allied Command Atlantic (ACLANT) and Allied Command Channel (ACCHAN). The NATO European and Atlantic Commands participate in the Joint Strategic Planning System at Omaha, Nebraska, but there is no Alliance Command specifically covering strategic nuclear forces. As for ballistic-missile submarines, the United States has committed a small number and Britain all hers to the planning control of SACEUR, and the United States a larger number to SACLANT. The Supreme Allied Commander Europe (SACEUR) and the Supreme Allied Commander Atlantic (SACLANT) have always been American officers; and the Commander-in-Chief Channel (CINCCHAN) and Deputy SACEUR and Deputy SACLANT British. SACEUR is also Com- mander-in-Chief of the United States forces in Europe. (i) ALLIED COMMAND EUROPE (ACE) has its headquarters known as SHAPE (Supreme Head- quarters, Allied Powers in Europe), at Casteau, near Mons, in Belgium. It is responsible for the 13 defence of all NATO territory in Europe excluding Britain, France, Iceland and Portugal and of all Turkey. It also has general responsibility for the air defence of Britain. The European Command has some 7,000 tactical nuclear warheads in its area. There is a very wide range in the kiloton spectrum. The number of delivery vehicles (aircraft, missiles and howitzers) is about 2,250, spread among all countries, excluding Luxembourg. The nuclear explosives them- selves, however, are maintained in American custody. Tactical nuclear bombs and missile war- heads are all fission. The average yield of the bombs stockpiled in Europe for the use of NATO tactical aircraft is about 100 kilotons, and of the missile warheads, 20 kilotons. About 60 division equivalents are available to SACEUR in peacetime. The Command has some 2,900 tactical aircraft, based on about 150 standard NATO airfields and backed up by a system of jointly financed storage depots, fuel pipelines and signal communications. The majority of the land and air forces stationed in the Command are assigned to SACEUR while the naval forces are earmarked. The 2nd French Corps of two divisions (which is not integrated in NATO forces) is stationed in Germany under a status agreement reached between the French and German Governments. Co- operation with NATO forces and commands has been agreed between the commanders concerned. The ACE Mobile Force (AMF), has been formed as a NATO force with particular reference to the northern or south-eastern flanks. Found by eight countries, it consists of eight infantry battalion groups, an armoured reconnaissance squadron and ground-support fighter squadrons, but has no air transport of its own. The following Commands are subordinate to Allied Command Europe: 

(a) Allied Forces Central Europe (AFCENT) has command of both the land forces and the air forces in the Central European Sector. Its headquarters are at Brunssum, Netherlands, and its Commander (CINCENT) is a German general. The forces of the Central European Command include 21 divisions assigned by Belgium, Britain, Canada, West Germany, the Netherlands and the United States and about 1,700 tactical aircraft. The Command is sub-divided into Northern Army Group (NORTHAG) and Central Army Group (CENTAG). NORTHAG, responsible for the defence of the sector north of the Göttingen- Liège axis, includes the Belgian, British and Dutch divisions, four German divisions and is supported by 2nd Allied Tactical Air Force (ATAF), composed of Belgian, British, Dutch and German units. The American forces, seven German divisions and the Canadian battle group are under the Central Army Group, supported by the 4th ATAF which includes American, German and Canadian units, and an American Army Air Defense Command.

(b) Allied Forces Northern Europe (AFNORTH) has its headquarters at Kolsaas, Norway, and is responsible for the defence of Denmark, Norway, Schleswig-Holstein and the Baltic Approaches. The Commander has always been a British General. Most of the Danish and Norwegian land, sea and tactical air forces are earmarked for it, and most of their active reserves assigned to it. Germany has assigned one division, two combat air wings and her Baltic fleet.

(c) Allied Forces Southern Europe (AFSOUTH) has its headquarters at Naples, and its Commander (CINCSOUTH) has always been an American admiral. It is responsible for the defence of Italy, Greece and Turkey, and for safeguarding communications in the Mediterranean and the Turkish territorial waters of the Black Sea. The formations available include 14 divisions from Turkey, 12 from Greece and 7 from Italy, as well as the tactical air forces of these countries. Other formations from these three countries have been earmarked for AFSOUTH, as have the United States 6th Fleet, and naval forces of Greece, Italy, Turkey and Britain. The ground-defence system is based on two separate commands: Southern, comprising Italy and the approaches to it, under an Italian Commander, and South-Eastern, comprising Greece and Turkey, under an American Commander. There is, however, an overall air command and there is a single naval command (NAVSOUTH), responsible to AFSOUTH with its headquarters in Malta. 14 A special air surveillance unit, Maritime Air Forces Mediterranean (MARAIRMED), is now operating Italian, British and American patrol aircraft from bases in Greece, Turkey, Sicily, Malta and Italy. French aircraft are participating in these operations. Its Commander, an American rear admiral, is immediately responsible to CINCSOUTH. The Allied On-Call Naval Force for the Mediterranean (NAVOCFORMED) has consisted of at least three destroyers, contributed by Italy, Britain and the United States, and three smaller ships provided by other Mediterranean countries, depending upon the area of operation.

(ii) ALLIED COMMAND ATLANTIC (ACLANT) has its headquarters at Norfolk, Virginia, and is res- ponsible for the North Atlantic area from the North Pole to the Tropic of Cancer, including Portuguese coastal waters. In the event of war, its duties are to participate in the strategic strike and to protect sea com- munications. There are no forces assigned to the command in peacetime except Standing Naval Force Atlantic (STANAVFORLANT), which normally consists, at any one time, of four destroyer- type ships. However, for training purposes and in the event of war, forces which are predominantly naval are earmarked for assignment by Britain, Canada, Denmark, Netherlands, Portugal and the United States. There are arrangements for co-operation between French naval forces and those of SACLANT. There are five subordinate commands: Western Atlantic Command, Eastern Atlantic Command, Iberian Atlantic Command, Striking Fleet Atlantic and Submarine Command. The nucleus of the Striking Fleet Atlantic has been provided by the American 2nd Fleet with up to six attack carriers; their nuclear role is shared with the missile-firing submarines.

(iii) ALLIED COMMAND CHANNEL (ACCHAN) has its headquarters at Northwood near London. The wartime role of Channel Command is to exercise control of the English Channel and the southern North Sea. Many of the smaller warships of Belgium, Britain and the Netherlands are earmarked for this Command, as are some maritime aircraft. There are arrangements for co-operation with French naval forces. 

### Policy 

The political and strategic guidance laid down in 1967 includes the concept of political warning time in a crisis and the possibility of distinguishing between an enemy's military capabilities and his political intentions. The strategic doctrine defined by the DPC in December 1967 envisaged that NATO would meet attacks on its territory with whatever force levels were appropriate. In June 1968 at the Ministerial Meeting at Reykjavik, the Council called on the countries of the Warsaw Pact to join in discussions of mutual force reductions, reciprocal and balanced in scope and timing, and repeated this invitation at their meeting in Rome in 1970. 

## BELGIUM 

Population: 9,800,000. Military service: 12 months. Total armed forces: 96,500. Estimated GNP 1970: \$24.9 billion. Defence budget 1971: 29,700 million francs (\$594,000,000). 50 francs = \$1. 

### Army: 71,500.

2 mechanized divisions of two brigades each. 1 paracommando regiment. 2 SSM battalions with Honest John. 2 SAM battalions with HAWK. 4 squadrons with Alouette II and Do-27. 330 Leopard and 175 M-47 med tanks; 135 M-41 It tanks; M-75 and AMX-VTT APC; M-108 105mm, M-44 and M-109 155mm and M-55 203mm SP howitzers; 203mm howitzers. 

#### RESERVES: 1 mech bde and 1 motorized bde. 

### Navy: 5,000.

5 fleet minesweepers/minehunters. 2 fleet minesweepers. 10 coastal minesweepers/minehunters. 10 inshore minesweepers. 2 support ships. 2 S-58 and 3 Alouette III helicopters. 

#### RESERVES: 3,000 trained. 

### Air Force: 20,000; 175 combat aircraft.

2 fighter-bomber squadrons with F-104G. 2 fighter-bomber squadrons with F-84F. 2 AWX squadrons with F-104G. 1 reconnaissance squadron with RF-84F. (The F-84F and RF-84F are being replaced by Mirage-VB.) (A combat squadron has 18-25 aircraft.) 33 C-119 and 18 C-47, Pembroke and DC-6 tpts. 11 HSS-1 helicopters. 8 SAM squadrons with Nike-Hercules. Para-Military Forces: 13,500 Gendarmerie. 

## BRITAIN 

Population: 56,000,000. Voluntary military service. Total armed forces: 380,900 (including 16,300 en- listed outside Britain). Estimated GNP 1970: \$121 billion. Defence budget 1971/72: £2,545 million (\$6,108 million). £1 = \$2.40. 

### Strategic Forces 4 SSBN each with 16 Polaris A-3 missiles. 

The Ballistic Missile Early Warning System (BMEWS) station at Fylingdales provides early warning of missile threats. 

### Army: 185,300 (including 14,200 enlisted outside Britain).

12 armoured regiments. 5 armoured car regiments. 43 infantry battalions. 3 parachute battalions. 6 Gurkha battalions. 1 special air service (SAS) regiment. 3 regts with Honest John SSM and 203mm how- itzers. 24 other artillery regiments. 1 SAM regiment with Thunderbird. 14 engineer regiments. 59 of the above units are organized in two armoured, twelve infantry, one parachute and one Gurkha brigades. EQUIPMENT: 900 Chieftain and Centurion med tanks; 105mm Abbot and M-107 175mm SP guns; M-109 155mm SP howitzers: 203mm howitzers; Honest John SSM; Vigilant and Swingfire ATGW; light aircraft and 30 Scout helicopters. 

### DEPLOYMENT: 

The Strategic Reserve - includes one div of three airportable bdes and two parachute bns of the United Kingdom Mobile Force (UKMF), and the SAS regiment. Germany - British Army of the Rhine (BAOR), of 54,900, includes three div HQ, one mech and five armd bdes, two armd car regts, two arty bdes and the Thunderbird SAM regt. In Berlin there is one 3,000-strong brigade. Far East (excl Hong Kong) - By the end of 1971 the force will be reduced to one bn gp in Singa- pore, and one Gurkha bn in Brunei. Hong Kong - five inf bns, one arty regt. Persian Gulf - two inf bns and support units (until end of 1971). Cyprus - UNFICYP: one inf bn and one air portable recce sqn. Garrison: one inf bn and one armd car sqn. Malta - one inf bn and one coy gp. Gibraltar - one inf bn. The Caribbean - one coy gp and engr det. 

#### RESERVES: 118,200 Regular Reserves. 49,000 Volun- teer reserves.

### Navy: 84,600 (including Fleet Air Arm and Marines). 

Submarines, attack: 2 nuclear-powered (SSN) (2 more are due to enter service in 1971-72); 17 diesel-powered. Surface Ships 2 aircraft carriers. 2 commando carriers. 2 assault ships. 1 GM cruiser with Seacat SAMs. 1 GM destroyer with Seadart SAM. 6 GM destroyers with Seaslug and Seacat SAM. 2 other destroyers. 29 general purpose (GP) frigates. 19 ASW frigates. 4 AA and 3 aircraft direction frigates. 47 MCM ships. Ships in reserve or undergoing refit or conversion include (in addition to the above): 2 SSN, 9 diesel submarines, 1 commando carrier, 2 GM cruisers, 1 GM destroyer, 1 other destroyer, 6 GP frigates, 3 ASW frigates, 1 aircraft direction frigate. 

### THE FLEET AIR ARM: 96 combat aircraft.

2 strike squadrons with Buccaneer. 2 air defence sqns with F-4K. 4 air defence sqns with Sea Vixen. (a combat squadron has 12 aircraft.) 8 helicopter sqns with Wessex. 3 helicopter sqns with Sea King. 3 helicopter sqns with Wasp and Whirlwind. THE ROYAL MARINES total about 8,000 men, and include 4 800-men Commandos. 

#### RESERVES (naval and marines): 24,200 regular and 7,800 volunteers. 

### Air Force: 111,000; about 500 combat aircraft.

8 medium bomber squadrons with Vulcan. 2 light bomber squadrons with Canberra. 3 strike squadrons with Buccaneer. 6 strike/attack/reconnaissance squadrons with F-4M. 1 ground-attack squadron with Hunter. 4 close support squadrons with Harrier. 9 air defence squadrons with Lightning. 1 air defence squadron with F-4K. 1 reconnaissance squadron with Victor 2. 4 reconnaissance squadrons with Canberra. 2 maritime patrol squadrons with Nimrod. 6 maritime patrol squadrons with Shackleton. (A combat squadron has 6-12 aircraft.) 3 tanker squadrons with Victor. 4 strategic tpt squadrons with VC-10, Belfast and Britannia. 8 tactical tpt sqns with Hercules and Argosy. 2 light communication squadrons with Andover. 7 helicopter squadrons with Wessex and Whirlwind. (SA-330 Puma are entering service.) There are 11 ground defence and AD squadrons of the Royal Air Force Regiment, some with Bloodhound and Tigercat SAM, and L-40/70 AA guns. (Rapier SAM are being introduced.) 

### DEPLOYMENT 

The Royal Air Force includes two operational home commands - Strike Command and Air Support Command, and four smaller overseas commands - RAF Germany, Near East Air Force, Air Force Gulf and Far East Air Force. Squadrons are deployed overseas as follows: Germany: 8,600. 4 F-4; 1 Buccaneer (a second is due to form during 1971); 2 Canberra, 2 Light- ning; 2 Harrier (a third is due to form by the end of 1971); 1 Wessex. Near East: (a) Cyprus - 2 Vulcan; 1 Lightning; 1 Hercules. (b) Malta - 1 Shackleton (converting to Nimrod); 1 Canberra. Gulf: 1 Hunter; 1 Shackleton; 1 Argosy; 1 Andover; 1 Wessex, (Until the end of 1971.) Far East: (a) mid-1971 - 1 Lightning 1 Shackleton; 1 Hercules; 1 Whirlwind. (b) after 1971 - some Nimrod aircraft and Whirlwind helicopters, based on Singapore.

#### RESERVES: 32,800 regular; about 400 volunteer. 

## CANADA 

Defence budget 1971-72: $Can1,822,500,000 ($US1,687,500,000). \$Can1.08 = SUS1.\* Population: 21,700,000. Voluntary military service. Total armed forces: 85,000. Estimated GNP 1970: \$US78.2 billion. 

### Army (Land)t 33,000. 

IN CANADA: Mobile Command. 1 airborne regiment. 3 combat groups each comprising: 3 infantry battalions. 1 reconnaissance regiment. 1 reduced light artillery regiment (of 2 batteries). Support units. One group is intended for operations in Europe, while part of it, an air transportable battalion group, is assigned to Allied Command Europe (ACE) Mobile Force. The other groups con- tribute to North American ground defence, and UN commitments. IN EUROPE: One mechanized battle group of about 2,800 men, with 32 Centurion tanks, 375 M-113 APC and 18 M-109 155mm SP howitzers. IN CYPRUS (UNFICYP): 460 men. RESERVES: about 18,000. 

### Navy (Maritime)t: 15,000.

4 submarines. 9 helicopter destroyer escorts. 11 ASW destroyer escorts. 6 coastal minesweepers. 1 ASW hydrofoil. 3 support ships. The Maritime Air Element consists of: 4 maritime patrol squadrons with Argus. 1 maritime patrol squadron with Tracker aircraft. 1 ASW squadron with Sea King helicopters. RESERVES: about 2,900. 

### Air Force (Air)t: 37,000; 162 combat aircraft. 

IN CANADA: Mobile Command:

2 CF-5 tactical fighter squadrons. 6 helicopter squadrons. Air Defence Command: 3 interceptor squadrons with CF-101 (due to be replaced in 1971 by F-101C). 2 SAM squadrons with Bomarc B. 28 surveillance and control radar squadrons. (The above are assigned to NORAD.)

-   The exchange rate has been allowed to fluctuate since 1 June 1970. t The Canadian Armed Services have been unified since February 1968, but for purpose of comparison with other countries, are presented here in traditional form. 17 1 CF-100 electronic warfare training squadron. Air Transport Command:

1 sqn with Boeing 707-320C transport/tankers. 2 sqns with C-130E Hercules. 2 sqns with CC-115 Buffalo and CC-138 Twin Otter. 2 sqns with Buffalo, and CH-113 Labrador helicopters. 1 sqn with CC-106 Yukon. 1 sqn with CC-109 Cosmopolitan and Falcon. IN EUROPE: 2 strike-attack and 1 reconnaissance squadrons, with CF-104. (A squadron has 6-18 aircraft.) RESERVES: 800, 

## DENMARK

Population: 4,990,000. Military service: 12 months. Total armed forces: 40,500. Estimated GNP 1970: \$16.0 billion. Defence budget 1971-72: 3,077,100,000 kroner (\$410,300,000). 7.5 kroner = \$1. 

### Army: 24,000. 

4 armoured infantry brigades. 1 battalion group. 3 artillery battalions. Centurion med tanks; M-41 It tanks; M-113 APC; M-109 155mm SP howitzers; 203mm howitzers; Honest John SSM\*; 12 Hughes 500M hel. RESERVES: 40,000 - 2 armd inf bdes and sup- port units to be formed from reservists within 72 hours. Local defence units form 15 inf bn gps and 15 arty btys. Volunteer Home Guard - 52,000. 

### Navy: 6,500.

6 submarines. 2 fast frigates. 4 helicopter frigates (fishery protection). 4 coastal escorts. 16 fast torpedo boats. 16 patrol boats (7 less than 100 tons). 4 fleet minelayers. 3 coastal minelayers. 8 coastal minesweepers. 4 inshore minesweepers. 9 seaward defence craft, 8 Alouette III helicopters. 

### Air Force: 10,000; 112 combat aircraft.

1 fighter-bomber squadron with F-35XD Draken. 2 fighter-bomber squadrons with F-100D/F. 2 interceptor squadrons with F-104G. 1 interceptor squadron with Hunter. 1 reconnaissance squadron with RF-84F (con- verting to RF-35 Draken during 1971). (A combat squadron has 16 aircraft.) 1 transport squadron with C-47 and C-54. 1 SAR squadron with S-61 helicopters. 4 SAM squadrons with Nike-Hercules. 4 SAM squadrons with HAWK. RESERVES: 3,000. Volunteer Home Guard - 4,000 with small patrol boats. RESERVES: Volunteer Home Guard - 8,000. 

## FRANCE 

Population: 51,225,000. Military service: 12 months. Total armed forces: 501,500. Estimated GNP 1970: \$148 billion. Defence Budget 1971: 28,873 million francs (\$5,202,000,000). 5.55 francs = \$1. 

### Strategic Forces

IRBM: the first 9-missile squadron is due to become operational during 1971§. SLBM: the first 16-missile SSBN is due to become operational during 1971+ Aircraft: Bombers: 36 Mirage IVA in 9 squadrons. Tankers: 9 KC-135F in 3 squadrons. Army: 329,000. M-47 and about 575 AMX-30 med tanks; AMX-13 It tanks; EBR hy and AML It armd cars; VTT-AMX APC; SP AMX 105mm guns and 155mm howitzers; 30mm twin SP AA guns; SS-11/Harpon ATGW.

5 mechanized divisions. 1 parachute division (2 brigades). 1 airportable motorized brigade. 2 Alpine brigades. 4 armoured car regiments. 2 motorized infantry regiments. 1 parachute battalion. 25 infantry battalions. 5 SSM battalions with Honest John.t 3 SAM regiments with HAWK. 

### DEPLOYMENT: 

Strategic Reserve: permanent element includes the para div and the air-portable bde.

§ It became operational on 2 August 1971. 5 SSBN are due to be built in all. + The nuclear warheads held under double-key arrangements with the USA were withdrawn in 1966. The tactical nuclear SSM Pluton is due to enter service in 1973. \* There are no nuclear warheads on Danish soil. Germany: About 62,000 incl two mech divs; 4 SSM regts with Honest John\*. About 1,700 in West Berlin. French Territory of the Afars and Issas: 2 battalions. Elsewhere in Africa: about 4,000 (see p. 64). Pacific Territories: 2 battalions. Caribbean: 1 battalion. The remaining troops are stationed in France for local defence (DOT). Their peacetime strength is about 61,500 men, including 35 battalions (infantry, light armour, artillery and engineer). RESERVES: Mobilization would bring the DOT up to a total of 80 infantry battalions, 5 armoured car regiments and support units. 

### Navy: 68,500 (including Naval Air Force). 

19 attack submarines. 2 aircraft carriers. 1 helicopter/aircraft carrier. 1 helicopter carrier. 2 assault landing ships. 1 anti-aircraft/command cruiser. 16 destroyers (4 GM, with Tartar SAM). 3 GM frigates with Malafon ASW missiles (2 with Masurca SAM). 27 frigates. 14 coastal escorts. 14 fleet minesweepers. 60 coastal minesweepers. 15 inshore minesweepers. 5 landing ships. 12 landing craft. 

### NAVAL AIR FORCE: 12,000; 200 combat aircraft. 

3 fighter-bomber sqns with Etendard IV-M. 2 interceptor sqns with F-8F. 3 reconnaissance sqns with Etendard IV-P. 3 ASW sqns with Alizé. (All the above can be flown from aircraft carriers.) 5 maritime recce sqns with Atlantic and P-2. 1 ASW helicopter sqn with Super-Frelon. 2 helicopter sqns with Alouette II\|III. DEPLOYMENT: For naval elements overseas see p. 64. 

### Air Force: 104,000; 500 combat aircraft. 

Air Defence Command (CAFDA) has:

3 interceptor squadrons with Mirage IIIC. 2 AWX interceptor squadrons with Vautour IIN. 3 interceptor squadrons with Super-Mystère B2. (Co-ordination is by the automatic STRIDA II air defence system.)

2nd CATAC - and includes: 8 fighter-bomber squadrons with Mirage IIIE. 1 fighter-bomber squadron with Mirage IIIB. 2 fighter-bomber squadrons with F-100D. 2 fighter-bomber squadrons with Mystère IVA. 3 tactical recce squadrons with Mirage IIIR/RD. Air Transport Command (COTAM) has: 3 tactical transport squadrons with Transall. 4 tactical transport squadrons with Noratlas. 1 heavy transport squadron with DC-6 and Br-765 Sahara and 2mixed transport squadrons. 4 squadrons with H-34 and Alouette II heli- copters. Tactical Air Force (FATAC) has: 2 subordinate Tactical Air Commands - 1st CATAC and FEDERAL REPUBLIC OF GERMANY DEPLOYMENT: 1 squadron of A-1D and 1 mixed transport squadron are stationed in the French Territory of the Afars and Issas. Other air ele- ments overseas are shown on p. 64. 

### Army: 327,000 (including the 35,000 Territorial Force). 

Population: 60,000,000 (excluding West Berlin). Military service: 18 monthst. Total armed forces: 467,000. Estimated GNP 1970: \$185 billion. Defence budget 1971: DM 21,816 million (\$5,961 million). DM 3.66 = \$11. Para-Military Forces: 65,000 Gendarmerie and 85,000 reserves (subordinate to the Ministry of Defence). 15,000 CRS (Compagnies Républi- caines de Sécurité) (subordinate to the Ministry of the Interior).

12 armoured brigades. 1 armoured regiment. 13 armoured infantry brigades. 3 rifle brigades. 2 mountain brigades. 3 airborne brigades. 11 SSM battalions with Honest John. 4 SSM battalions with Sergeant. 1,050 M-48A2 Patton and 2,250 Leopard med tanks; 1,770 HS-30 and 3,140 M-113 APC; 1,100 tank destroyers with 90mm guns or ATK msls; 250 105mm, 375.155mm, 150 175mm and 75 203mm SP guns; 500 SP 40mm AA guns; about 460 Bell-47, UH-1D Iroquois and Alouettet A Government Commission has proposed a reduction to 16 months. + The exchange rate has been allowed to fluctuate since 9 May 1971. \* See footnote + on p. 17 19 II helicopters, and 80 Do-27 light aircraft. RESERVES: 540,000 on immediate recall.

### Navy: 36,000 (including Naval Air Arm).

11 coastal submarines. 3 GM destroyers with Tartar SAM. 9 destroyers. 6 fast frigates. 2 frigates. 5 fleet utility vessels. 13 escort and support ships. 24 coastal minesweepers/minehunters. 30 fast minesweepers. 18 inshore minesweepers. 2 minelayers. 40 fast patrol boats. 2 landing ships. 22 landing craft. NAVAL AIR ARM: 6,000; 100 combat aircraft. 4 fighter-bomber/recce squadrons with F-104G.

2 MR squadrons with BR-1150 Atlantic. 23 S-58 SAR helicopters, being replaced by SH-3D. RESERVES: 36,000 on immediate recall. 

### Air Force: 104,000; 504 combat aircraft. 

10 fighter-bomber squadrons with F-104G. 4 It ground-attack/strike squadrons with G-91. 4 interceptor squadrons with F-104G. 4 heavy reconnaissance squadrons with RF-104G (replacement with RF4-E Phantom II has started). 4 reconnaissance squadrons with G-91. 6 transport squadrons with C-160 Transall. 4 helicopter squadrons with UH-1D. (Fighter, fighter-bomber, reconnaissance and light- strike squadrons have 15-21 aircraft, and tpt squadrons up to 18.) 3 SSM battalions with Pershing. 24 SAM batteries with Nike-Hercules. 36 SAM batteries with HAWK. RESERVES: 87,000 for immediate recall. 


## GREECE

### Army: 118,000. 

Para-Military Forces: 18,500 Border Police with Saladin armoured cars and coastal patrol boats. 

11 infantry divisions (3 close to full strength). 1 armoured division. 1 commando brigade. 2 SSM battalions with Honest John. 1 SAM battalion with HAWK. 200 M-47, 220 M-48 and 50 AMX-30 med tanks; M-24, M-26 and M-41 It tanks; M-8 and M-20 armd cars; M-3 scout cars; M-2, M-59 and M-113 APC; 105mm, 155mm and M-107 175mm SP guns; 105mm, 155mm and 203mm howitzers; 40mm, 75mm and 90mm AA guns. 

### Navy: 18,000.

2 submarines (4 more to be delivered by West Germany). 8 destroyers. 4 destroyer escorts. 7 coastal patrol vessels. 2 minelayers. 20 coastal minesweepers. 12 fast torpedo boats (less than 100 tons) (4 FPB, with Exocet SSM, are on order from France, the first due for delivery in 1971). 8 tank landing ships. 6 medium landing ships. 1 dock landing ship. 8 landing craft. 8 HU-16 maritime patrol aircraft. 

Population: 8,960,000. Military service: 24 months. Total armed forces: 159,000. Estimated GNP 1970: \$9.2 billion. Estimated defence expenditure 1971: 10,138 million drachmas (\$337,900,000). 30 drachmas = \$1. 

### Air Force: 23,000; 216 combat aircraft.

3 fighter-bomber squadrons with F-84F. 2 fighter-bomber squadrons with F-104G. 4 interceptor squadrons with F-5A. 1 interceptor squadron with F-102A. 1 photo-reconnaissance squadron with RF-5. 1 reconnaissance squadron with RF-84F. (A combat squadron has up to 18 aircraft.) 30 C-47 and C-119G, and 25 Noratlas tpts. 1 helicopter squadron with 12 H-19 and 6 AB-205. 1 helicopter squadron with 10 Bell 47G. 1 SAM battalion with Nike-Hercules. Para-Military Forces and Reserves: 25,000 Gen- darmerie. 200,000 Reserves. Population: 54,000,000. Military service: Army and Air Force, 15 months; Navy, 24 months. Total armed forces: 414,000 (excluding Cara- binieri). Estimated GNP 1970: \$93.2 billion. 

ITALY 20 Defence budget 1971: 1,657 billion lire (\$2,651,000,000). 625 lire=\$1. Army: 295,000

2 armoured divisions. 5 infantry divisions. 1 independent cavalry brigade. 4 independent infantry brigades. 5 Alpine brigades (of 5,000 men each). 1 parachute brigade. 1 SSM brigade (incl 4 bns with Honest John). 4 SAM battalions with Hawk. 800 M-47 and 200 M-60 med tanks (deliveries of 800 Leopard have started); M-24 It tanks; M-113 APC; M-44, M-56, M-107 and M-109 SP guns; M-42 SP AA guns. Navy: 45,000 (incl air arm and marines).

9 submarines. 3 GM cruisers with Terrier SAM and ASW heli- copters. (one with ASROC ASW missiles). 2 GM destroyers with Tartar SAM. 2 destroyer leaders. 7 ASW destroyers. 10 destroyer escorts. 16 coastal escorts. 4 ocean minesweepers. 37 coastal minesweepers. 20 inshore minesweepers. 7 fast patrol boats. 7 motor torpedo boats (less than 100 tons). 1 command ship. 3 landing ships. 2 marine infäntry battalions. NAVAL AIR ARM: 3 maritime patrol squadrons with S-2 (due to be replaced by Atlantic by mid-1972), HU-16A SAR aircraft and 50 Bell-47, SH-34, AB-204 and SH-3D SAR helicopters. Air Force: 74,000; 300 combat aircraft. 3 fighter-bomber squadrons with F-104G. 1 fighter-bomber squadron with G-91Y. 1 fighter-bomber squadron with F-84F. 4 light attack squadrons with G-91R. 4 AWX squadrons with F-104G. 2 AWX squadrons with F-104S. 1 AWX squadrons with F-86K. 3 recce squadrons with RF-84F and RF-104G. 3 transport squadrons with C-119 (delivery. of 14 C-130E Hercules is due to begin in 1971). 1 transport sqn with C-47, Convair 440 and DC-6. (A combat squadron ('gruppo') has 12-18 aircraft, and a transport squadron 16.) 6 SAM groups with Nike-Hercules. LUXEMBOURG Population: 342,000. Voluntary military service. Total armed forces: 550. Estimated GNP 1970: \$0.91 billion. Defence budget 1971: 429,600,000 francs (\$8,592,000). 50 francs = \$1. Army: 550. A light infantry battalion (4 companies). Some anti-tank guns and mortars. Para-Military Forces and Reserves: 80,000 Cara- binieri Corps. About 650,000 trained reservists. Para-Military Forces: 350 Gendarmerie. 

## NETHERLANDS

Population: 13,175,000. Military service: Army, 16-18 months; Navy and Air Force, 18-21 months. Total armed forces: 116,500. Estimated GNP 1970: \$31.3 billion. Defence budget 1971: 4,203 million guilders (\$1,161,000,000). 3.62 guilders=\$1

### Army: 76,000. 

2 armoured brigades. 4 armoured infantry brigades. 2 SSM battalions with Honest John. 400 Centurion (with 105mm guns) and 200 Leopard med tanks (285 more Leopards are being de- livered); 120 AMX-13 It tanks; M-106, M-113 and M-577 amphibious APC; AMX-VTT and YP-408 APC; AMX-105, M-109 155mm, M-107 175mm and M-110 203mm SP howitzers. RESERVES: 1 inf div, and the remaining corps troops, incl 1 indep inf bde, are to be completed by call- up of reservists.

### Navy: 19,000 including 2,900 marines and 2,000 naval air force. 

5 submarines (2 more due to become operational in 1971/72). 2 cruisers (one GM with Terrier SAM). 6 GM frigates with Seacat SAM. 12 destroyers. 6 corvettes. 6 support escorts. 5 patrol vessels. 36 coastal minesweepers and minehunters. 16 inshore minesweepers. 1 fast combat support ship.* The exchange rate has been allowed to fluctuate since 9 May 1971. 

NAVAL AIR ARM: 5 Atlantic, and about 30 P-2 and S-2 MR aircraft. 15 Wasp, SH-34J and AB-204B ASW helicopters. 

### Air Force: 21,500; 126 combat aircraft.

2 fighter-bomber squadrons with F-104G. 2 fighter-bomber squadrons with NF-5A. 2 interceptor squadrons with F-104G. 1 photo-reconnaissance squadron with RF-104G. (A combat squadron has 18 aircraft.) 1 transport squadron with F-27. 3 observation and communication squadrons (under Army command) with Alouette III heli- copters, and Super-Cub and Beaver light aircraft. 8 SAM squadrons with Nike-Hercules. 9 SAM squadrons with HAWK. Para-Military Forces: 3,200 Gendarmerie (Royal Maréchaussée). 

## NORWAY Population: 3,915,000. 

Military service: Army, 12 months; Navy and Air Force, 15 months. Total armed forces: 35,900. Estimated GNP 1970: \$12.46 billion. Defence budget 1971: 2,932 million kroner (\$410,640,000). 7.14 kroner = \$1. 

### Army: 18,000. 

The peacetime establishment includes 1 brigade group in North Norway, independent battalions and supporting elements and training units. Leopard and M-48 med tanks; M-24 It tanks and M-8 armd cars; M-113 and BV-202 APC; M-109 155mm SP howitzers; L-18 and L-19 It aircraft. RESERVES: mobilization would produce 11 Regi- mental Combat Teams (brigades), supporting units and territorial forces totalling 157,000. 

### Navy: 8,500 (incl 800 coastal artillery).

15 coastal submarines. 5 frigates. 2 coastal escorts. 10 coastal minesweepers. 5 minelayers. 21 gunboats (refitting with Penguin SSM). 6 torpedo boats. 20 torpedo boats (less than 100 tons). 2 armed depôt and training ships. A number of coastal artillery batteries.


5 light attack squadrons each with 16 F-5A. 1 AWX fighter squadron with 20 F-104G. 1 photo-reconnaissance squadron with 16 RF-5A. 1 maritime patrol squadron with 5 P-3B. 1 transport squadron with 6 C-130 and 4C-47. 2 helicopter squadrons with UH-1. 4 SAM batteries with Nike-Hercules. Air Force: 9,400; 121 combat aircraft. RESERVES: 10,600, providing 12 airfield defence It AA bns. Home Guard (all services): 75,000. 

## PORTUGAL 

Population: 9,730,000. Military service: Army, 24 months; Air Force, 36 months; Navy, 48 months. Total armed forces: 218,000 (about 60,000, incl those locally enlisted, are in Angola, 45,000 in Mozambique, and 25,000 in Portuguese Guinea). Estimated GNP 1970: \$6.1 billion. Estimated defence expenditure 1970: 11,444 million escudos (\$398,100,000). 28.75 escudos= \$1. 

### Army: 179,000. 

2 tank regiments. 8 cavalry regiments and battalions. 35 infantry regiments and battalions. 17 coastal artillery regiments and battalions. M-47 and M-4 med tanks; M-41 It tanks; Humber Mark IV and EBR-75 armd cars; AML-60 scout cars; FV-1609 and M-16 half-track APC; 105mm and 140mm howitzers. DEPLOYMENT: Some of the above units form 2 infantry divisions, at or below half-strength, in Portugal. About 25 infantry regiments and supporting units are in the provinces in Africa. 

### Navy: 18,000 (including 3,300 marines).

4 submarines. 11 frigates. 6 corvettes. 14 coastal patrol vessels. 4 ocean minesweepers. 12 coastal minesweepers. 41 patrol launches (less than 100 tons). 5 landing craft (LCT-type). 58 small landing craft (less than 100 tons). RESERVES: 12,000. Air Force: 21,000; 150 combat aircraft.

2 light bomber sqns with B-26 Invader and PV-2. 1 fighter-bomber squadron with F-84G. 2 light-strike squadron with G-91. 1 interceptor squadron with F-86F. 6 COIN flights with armed T-6. 22

1 maritime patrol squadron with P-2 V5. (A combat squadron has 10-25 aircraft.) 22 Noratlas, 16 C-47, 11 DC-6 and 15 C-45 transports. 13 T-33, 25 T-37 and 35 T-6 reconnaissance/ trainers. Other aircraft include 11 Do-27 and about 85 Alouette II\|III and SA-330 Puma helicopters. 1 parachute regiment of 4,000. 

DEPLOYMENT: 1 parachute battalion in each of the African provinces. 1 G-91 squadron in Mozambique. Para-Military Forces and Reserves: 9,700 National Republican Guard. 500,000 Reserves. 

## TURKEY 2 parachute battalions. 

Population: 36,100,000. Military service: 20 months. Total armed forces: 508,500. Estimated GNP 1970: \$13.7.billion. Defence budget 1971-72: 6,695 million liras (\$446,000,000). 15 liras = \$1 (before 9 August 1970 9 = \$1). 

### Army: 420,000.

1 armoured division. 12 infantry divisions. 4 armoured brigades. 4 armoured cavalry brigades. 1 mechanized infantry division. 3 mechanized infantry brigades. M-47 and M-48 med tanks; M-24, M-26 and M-41 It tanks; M-36 tank destroyers; M-8 armd cars; M-59 and M-113 APC; 105mm and 155mm SP guns; 105mm, 155mm and 203mm howitzers; 40mm, 75mm and 90mm AA guns; Honest John SSM. 

### Navy: 38,500.

12 submarines. 10 destroyers. 6 coastal escorts. 11 motor torpedo boats (2 less than 100 tons). 10 motor launches. 15 coastal minesweepers. 4 inshore minesweepers. 1 fleet minelayer. 5 coastal minelayers. A number of landing craft. 

### Air Force: 50,000; 360 combat aircraft.

2 fighter-bomber squadrons with F-104G. 4 fighter-bomber squadrons with F-100. 4 fighter-bomber squadrons with F-5. 4 interceptor squadrons with F-5. 2 interceptor squadrons with F-86 (in store) 2 AWX squadrons with F-102A. 2 reconnaissance squadrons with RF-84F. (A combat squadron has 10-25 aircraft.) 4 tpt sqns incl 50 C-47, 3 C-54 and 5 C-130. 2 SAM battalions (6 batteries) with Nike-Hercules. Para-Military Forces: 75,000 Gendarmerie (incl 3 mobile brigades). 

## OTHER EUROPEAN COUNTRIES 

## ALBANIA 

Population: 2,190,000. Military service: Army, 2 years; Air Force, Navy and special units, 3 years. Total regular forces: 42,000. Estimated GNP 1970: \$0.9 billion. Estimated defence expenditure 1971: 580 million leks (\$116,000,000). 5 leks = \$1. 

### Army: 35,000. 

1 tank brigade. 6 infantry brigades. Some light shore batteries. 70 T-34 and 15 T-54 med tanks; 20 BA-64, BTR-40 and BTR-152 APC; SU-76 SP guns; 122mm and 152mm guns and howitzers; 45mm, 57mm, 76mm and 85mm ATk guns; 37mm, 57mm and 85mm AA guns; a few SA-2 SAM. 

### Navy: 3,000. 

4 submarines. 4 ASW patrol vessels. 30 MTB and patrol boats (less than 100 tons). 8 inshore minesweepers. Some SSM deployed around the ports of Durazzo and Valona. 

### Air Force: 4,000: 72 combat aircraft. 

3 fighter squadrons with MiG-17. 2 fighter squadrons with MiG-15. 1 interceptor squadron with MiG-19. (A combat squadron has 12 aircraft.) 1 transport squadron with An-2 and Il-14. About 8 Mi-1 and Mi-4 helicopters. Para-Military Forces: 37,500. Internal security force-12,500. Frontier force - 25,000. 

## AUSTRIA

Population: 7,445,000. Military service: 9 months (to be reduced to 6 months during 1971). Total armed forces: 48,350. Estimated GNP 1970: \$14.3 billion. Defence budget 1971: S4,283 million (\$170,138,000) 24.75 schillings = \$1 (before 9 May 1971 26 = \$1). 

### Army: 44,000.

4 reduced strength infantry brigades. 3 reduced strength mechanized brigades. .3 tank battalions. 3 independent air defence battalions. 150 M-47 and 120 M-60 med tanks; 40 M-41 and 60 AMX-13 It tanks; 400 G1-2K APC; 105mm and 155mm howitzers, and 155mm guns; JPz-4K SP ATK guns; 84mm Carl Gustav ATGW; 130 mm rocket launchers; 38 M-42 SP AA guns; 20mm and 35mm Oerlikon and 40mm Bofors AA guns. 

### Air Force\*: 4,350; 23 combat aircraft. 

17 Saab 105 fighter-bombers. 6 J-29F Tunnan fighter-bombers. 35 Magister, Vampire and Sufir trainers. 19 Cessna L-19 light reconnaissance aircraft. 1 transport squadron with 3 Beaver and 2 Skyvan. 22 AB-204, 23 Alouette and 12 AB-206 helicopters. 

## FINLAND 

Para-Military Forces: 12,000 Gendarmerie. Population: 4,600,000. Military service: 8-11 months. Total armed forces: 39,500. Estimated GNP 1970: \$10.3 billion. Defence budget 1971: 646 million markkaa (\$153,800,000). 4.2 markkaa = \$1.

### Army: 34,000. 

1 armoured brigade (at about half strength). 6 infantry brigades (at about 35 per cent strength). 8 independent infantry battalions. 2 coastal artillery regiments. 3 coastal artillery battalions. 1 anti-aircraft regiment. 4 anti-aircraft battalions. T-54, T-55, and Charioteer med tanks; PT-76 It tanks; BTR-50P APC; 105mm, 122mm and 130mm guns; 122mm and 152mm howitzers; 81mm and 120mm mortars; Vigilant and SS-11 ATGW; ZSU-57, 35mm Oerlikon and 40mm Bofors AA guns. 

### Navy: 2,500. 

3 frigates (one used as training ship). 2 corvettes. 1 patrol boat with Mk 66 SSM. 15 fast patrol boats (less than 100 tons). 2 coastal minelayers. 5 patrol boats (ex-inshore minesweepers). \* Austrian air units are an integral part of the Army but for purposes of comparison have been listed separately. 

### Air Force: 3,000; 48 combat aircraft. 

3 fighter sqns with MiG-21F and Gnat Mark 1. 12 Magister armed trainers. About 100 other trainers, incl 70 Magister, 30 Safir, and a few MiG-15/MiG-21 UT1. About 10 C-47 and Beaver transports. Hound, Alouette II and 4 AB-204B helicopters. Para-Military Forces and Reserves: 3,000 Frontier defence tps. 650,000 reserves. 

## SPAIN

Population: 33,600,000. Military Service: 18 months. Total armed forces: 301,000. Estimated GNP 1970: \$32.3 billion. Defence budget 1971: 47,724 million pesetas (\$681,000,000). 70 pesetas = \$1. 

### Army: 220,000.

1 armoured division. 1 mechanized infantry division. 1 motorized infantry division. 2 mountain divisions. 12 independent infantry brigades. 1 armoured cavalry brigade. (All above are about 70 per cent strength.) 1 high mountain brigade. 1 airportable brigade. 1 parachute brigade. 2 artillery brigades. 1 SAM battalion with HAWK. M-47 and M-48 med tanks; M-24 and M-41 It tanks; Greyhound armd cars; AML-60/90 and M-3 scout cars; M-113 APC; 105mm and 155mm SP guns; 105mm, 155mm and 203mm howitzers; 90mm SP AT guns. Navy: 47,500 including 6,000 marines. 3 submarines. 1 helicopter carrier. 1 cruiser. 16 ASW destroyers. 3 destroyers. 8 frigates. 6 frigate-minelayers. 6 corvettes. 1 ASW patrol vessel. 3 torpedo boats. 13 fleet minesweepers. 12 coastal minesweepers. 8 landing ships. 3 ASW helicopter squadrons. 1 light helicopter squadron.

12 Mirage-IIIE fighter-bombers. 50 F-5 fighter-bombers. 55 HA-200 fighter-bombers. (36 F-4C fighter-bombers are being delivered.) 21 F-104G interceptors. 48 F-86F interceptors. 25 T-6 armed trainers. 1 ASW squadron with 11 Hu-16B. About 150 transport aircraft and helicopters, including C-47, C-54, 12 Caribou and 20 Azor. 

### Air Force: 33,500; 221 combat aircraft. 

Para-Military Forces: 65,000 Guardia Civil DEPLOYMENT (outside mainland Spain): Total strength: 41,000. These include mechanized and commando forma- tions of the Spanish Foreign Legion, elements of 3 divisions and support units. Balearic Islands: 6,000. Canary Islands: 8,000. Ceuta: 8,000 incl 1 regt of the Foreign Legion. Melilla: 9,000 incl 1 regt of the Foreign Legion. Spanish Sahara: 10,000 incl 2 regts of the Foreign Legion. 

## SWEDEN

Population: 8,125,000. Military service: Army and Navy, 9-15 months; Air Force, 9-14 months. Total armed forces: 23,000 regulars and 50,300 conscripts (total mobilizable strength 750,000). Estimated GNP 1970: \$31.2 billion. Defence budget 1971-72: 6,165 million Swedish kronor (\$1,192,000,000). 5.17 kronor= \$1. 

### Army: 12,500 regulars; 36,500 conscripts; 100,000 reservists called up each year for 18-40 days' training.

7 armoured regiments. 15 infantry regiments. 7 artillery regiments. 6 anti-aircraft artillery regiments. 1 parachute training unit. (All in cadre form.) 1 SAM battalion with HAWK. Centurion and STRV-103 med tanks; STRV-74 It tanks; IKV-91 amphibious tanks; Pbv-301/-302 APC; 105mm and 155mm SP howitzers; 155mm SP guns; 105mm and 155mm guns; 75mm, 105mm and 155mm howitzers; 90mm ATK guns; SS-11, Bantam, Carl Gustav and Miniman ATGW; 57mm SP, 20mm and 40mm AA guns; Redeye SAM. 

### Navy: 4,700 regulars; 7,400 conscripts.

23 submarines. 2 GM destroyers with Rb-08 SSM. 4 GM destroyers with Seacat SAM. 2 other destroyers. 7 fast anti-submarine frigates. 17 heavy torpedo boats. 25 motor torpedo boats (less than 100 tons). 1 minelayer/submarine depot ship. 18 coastal minesweepers. 17 inshore minesweepers (8 less than 100 tons). 5 coastal artillery regiments with 75mm, 105mm, 120mm, 152mm and 210mm guns; Rb-08 and Rb-52 (SS-11) SSM. 10 Vertol and 10 AB-206A helicopters. 

### Air Force: 5,800 regulars; 6,400 conscripts; 650 combat aircraft. 

10 attack squadrons with A-32A Lansen (with Rb-04 ASM) (replacement by the AJ-37 Viggen is due to start in 1971). 13 AWX squadrons with J-35 Draken F. 8 AWX squadrons with J-35 Draken A/D. 2 recce/fighter squadrons with S-32C. 3 recce/day-fighter squadrons with S-35E. (A combat squadron has up to 18 aircraft.) 1 transport squadron with 2 C-130E and 7 C-47. 1 heavy helicopter squadron with 10 Vertol-107. 6 SAM squadrons with Bloodhound 2. There is a fully computerized, fully automatic control and air surveillance system, Stril 60, co-ordinating all air defence components. Para-Military Forces: Voluntary defence organiza- tions - 325,000, including 90,000 women. 

## SWITZERLAND 

Population: 6,375,000. Military service: 4 months initial training, followed by reservist training of three weeks a year for 8 years, two weeks for 3 years, and one week for 2 years. Total armed forces: 5,500 regulars and 24,000 con- scripts (total mobilizable strength 600,000; reservists can be fully mobilized within 48 hours). Estimated GNP 1970: \$20.5 billion. Defence budget 1971: 1,909,200,000 francs (\$459,000,000). 4.08 francs= \$1 (before 9 May 1971 4.3 = \$1).

division and 2 infantry divisions each. There are also 17 frontier, fortress and 'redoubt' brigades, and 48 artillery battalions. 300 Centurion and 150 Pz-61 med tanks; 200 AMX-13 It tanks; 1,000 M-113 APC; 155mm SP howitzers; 105mm guns and howitzers; 81mm and 120mm mortars. Air Force: (including Air Defence troops)\*; 3,000 regular; 7,000 conscripts; 40,000 reservists (maintenance by civilians); 315 combat aircraft. 13 ground support squadrons with Venom FB 50. 2 interceptor squadrons with Mirage-IIIS. 5 interceptor squadrons with Hunter F-58 (with Sidewinder AAM). 1 reconnaissance squadron with Mirage-IIIR. (A combat squadron has 15 aircraft.) 20 transports including 3 Ju-52/3 and 6 Do-27. 80 helicopters including 60 Alouette II\|III. 40 AA batteries with Oerlikon twin 35mm cannon. 2 SAM battalions with Bloodhound 2. 

### Army: 2,500 regular training cadre; 17,000 con- scripts; 530,500 reservists. 

The militia-style Army is organized into 4 corps. 1 corps, for the defence of the Alps, consists of 3 mountain divisions; the other 3 corps, for the defence of the plain, consist of an armoured \## YUGOSLAVIA Population: 20,800,000. Military service: 18 months. Total armed forces: 233,000. Estimated GNP 1970: \$11.8 billion. Defence budget 1971: 8,838 million dinars (\$596,000,000). 15 dinars = \$1 (before 23 Jan. 1971 12.5 dinars = \$1). 

### Army: 195,000. 

9 infantry divisions. 14 armoured brigades. 31 independent infantry brigades. 1 airborne brigade. 1 marine infantry brigade. T-54/55, T-34, M-47 and 650 M-4 med tanks; PT-76 and 35 AMX-13 It tanks; M-3, BTR-50, BTR-60P and BTR-152 APC; SU-100 SP guns; 105mm and 155mm howitzers; 50mm, 57mm, 75mm and 76mm ATk guns; SU-57 SP AA guns; SA-2 SAM. 

### Navy: 18,000.

5 submarines. 1 destroyer. 3 patrol vessels. 16 submarine chasers. 4 coastal minesweepers. 20 inshore minesweepers (12 less than 100 tons). \* Swiss Air Force and Air Defence Troops are an integral part of the Army, but are listed here separately for purposes of comparison. 

10 Osa-class patrol boats with Styx SSM. 67 motor torpedo boats (55 less than 100 tons). 35 landing craft. 25 coastal artillery batteries. 

### Air Force: 20,000; 330 combat aircraft.

10 GA squadrons with F-84, Kraguj and Jastreb. 10 fighter/interceptor squadrons with F-86D/E and MiG-21F/PF. 2 reconnaissance squadrons with RT-33. (A combat squadron has 15 aircraft.) 60 Galeb trainers. 25 Li-2, Beaver, C-47 and II-14 transports. 50 Whirlwind and Mi-4, and some Alouette III helicopters. 8 SAM batteries with SA-2. Para-Military Forces: 19,000 Frontier Guards. 1,000,000 Territorial defence force (planned to increase to 3,000,000).
