# The Middle East and the Mediterranean

## Multilateral Agreements 

The members of the Central Treaty Organization (CENTO) are Britain, Iran, Pakistan and Turkey, with the United States as an associate. All sit on the Military, Economic and Counter-Subversion Committees and on the Permanent Military Deputies Group. The Treaty provides for mutual co-operation for security and defence but has no international command structure, nor forces allocated to it. For the local powers, the economic organization of Regional Co-operation for Development (RCD), which arose out of CENTO, may today be more important.

## Bilateral Agreements

A number of external powers have military arrangements with countries in the region. The United States has varying types of security assistance agreements and provides significant military aid on either a grant or credit basis to Greece, Turkey, Portugal, Spain, Morocco, Tunisia, Lebanon, Jordan, Saudi Arabia and Israel. It provides, in addition, a significant amount of military equip- ment on a cash sales basis to many countries, notably Israel, Spain and Jordan. For grant military assistance purposes Greece and Turkey are considered forward defence areas and Spain is considered a base rights country. Communication bases are maintained in Morocco under informal arrange- ments. The Soviet Union has a military assistance agreement, concluded in December 1970, and a 15 year treaty of friendship and co-operation, signed in May 1971, with the UAR. Important military assistance is also provided to Algeria, Iraq, Sudan and Syria which may be covered by more informal arrangements. The People's Republic of China has supplied arms to Albania, and has a treaty of friendship with the Yemen. Britain has defence commitments to Cyprus, Gibraltar, and Malta,\* and has proposed defence arrangements with the lower Gulf States after her withdrawal from the Persian Gulf at the end of 1971. Britain is also an important arms supplier for the Gulf Sheikhdoms, Saudi Arabia and Jordan. France has a pilot training agreement with Morocco but no other formal commitments in the region. The facilities provisions of the Evian agreements with Algeria lapsed at the end of 1970 with the return of the Bou-Sfer airbase to Algeria. France sells arms to a number of countries, notably to Libya. 

## Arrangements within the region (between Arab states)

Algeria, Iraq, Jordan, Kuwait, Lebanon, Libya, Morocco, Saudi Arabia, South Yemen, Sudan, Syria, Tunisia, the UAR and Yemen are members of the League of Arab States. Among its sub- sidiary bodies are the Arab Defence Council set up in 1950 and the Unified Arab Command organ- ized in 1964. Defence agreements were concluded by the UAR with Syria in November 1966 and Jordan in May 1967 to which Iraq later acceded. These agreements provided for the establishment of a Defence Council and a Joint Command. The loosely associated Eastern Front Command, comprising Iraq, Jordan, the Palestine Liberation Army and Syria, was reorganized in December 1970 into separate Jordanian and Syrian commands. Iraq and Syria concluded defence pacts in May 1968 and July 1969. The proposed Union of Arab Republics, announced by Libya, Syria, and the UAR in April 1971, would provide for a common defence policy and a Federal Defence Council. Sudan has announced its intention to join. \* The Malta and British Governments are discussing the 1964 Defence Agreement with a view to revising its provisions. 28 

## ALGERIA 

Population: 14,150,000. Military service: limited conscription. Total armed forces: 60,250. Estimated GNP 1970: \$4.4 billion. Defence budget 1971: 490 million dinars (\$99,200,000). 4.94 dinars = \$1. 

### Army: 53,000. 

4 motorized infantry brigades. 1 parachute brigade. 3 independent tank battalions. 50 independent infantry battalions. 12 companies of desert troops. 5 independent artillery battalions. 200 T-34, 200 T-54 and 50 T-55 med tanks; AMX- 13 It tanks; 350 BTR-152 APC; 25 SU-100 and 6 JSU-152 SP guns; 85mm guns, 122mm and 152mm howitzers; 140mm and 240mm RL.

### Navy: 3,250.

6 coastal escorts. 2 fleet minesweepers. 1 coastal minesweeper. 8 Komar- and 1 Osa-class patrol boats (Styx SSM). 8 P-6 torpedo boats. 

### Air Force: 4,000; 142 combat aircraft. 

24 II-28 light bombers. 20 MiG-15, 40 MiG-17 FGA. 30 MiG-21 interceptors. 28 Magister armed trainers. 8 An-12 and 3 Il-18 transports. 3 Mi-1, 40 Mi-4, 7 Hughes-269A and 2 SA-330 helicopters. 1 SAM battalion with SA-2. Para-Military Forces: 8,000. Gendarmerie with 50 AML armoured cars. 

## IRAN 

Population: 29,500,000. Military service: 2 years. Total armed forces: 181,000. Estimated GNP 1970: \$10.9 billion. Defence budget 1971-72: 77,500 million rials (\$1,023,000,000). 75.75 rials = \$1. 

### Army: 150,000. 

3 armoured divisions. 3 infantry divisions. 4 independent infantry brigades. 1 SAM battalion with HAWK. 400 M-47 and 460 M-60A1 med tanks; 100 M-24 It tanks; 100 M-8 and 140 M-20 armd cars; 300 M-113, 270 BTR-50 and 300 BTR-60 APC; 75mm, 105mm and 155mm howitzers; 40mm, 57mm and 85mm AA guns. 8 Huskie helicopters. (Further helicopters are being delivered.) 

### Navy: 9,000.

1 destroyer. 1 frigate (4 with Seacat SAM are being delivered). 4 corvettes. 4 patrol boats. 4 coastal minesweepers. 2 inshore minesweepers. 8 SRN-6 and 2 Wellington hovercraft (less than 100 tons). 4 landing craft.

### Air Force: 22,000; 140 combat aircraft.

2 fighter-bomber squadrons with F-4D, with Sidewinder and Sparrow AAM (32 F-4E are on order). 5 fighter-bomber squadrons with F-5. 20 F-86 AWX (being phased out). 9 RT-33 reconnaissance aircraft. Transports include 10 C-47, 26 C-130E and 6 Beaver (30 C-130H are being delivered). Helicopters include 10 Huskie, 45 AB-205 and 16 Super-Frelon. (Further helicopters are being delivered.) Tigercat SAM. (Rapier SAM are on order.) Para-Military Forces: 40,000. Gendarmerie with 30 AB-206 helicopters. 

## IRAQ 

Population: 9,250,000. Military service: 2 years. Total armed forces: 95,250. Estimated GNP 1970: \$3.12 billion. Estimated defence expenditure 1970-71: 84,700,000 dinars (\$237,160,000). 1 dinar = \$2.8. 

### Army: 85,000. 

2 armoured divisions. 4 infantry divisions (each of 4 brigades). 800 T-54 and T-55, and 60 T-34/85 med tanks; 45 PT-76 It tanks; 115 AML armd cars; 60 Ferret scout cars; BTR-152 APC; artillery includes 300 Soviet 120mm and 130mm guns. 

### Navy: 2,000. 

3 submarine chasers. 12 motor torpedo boats (less than 100 tons). 10 patrol boats (less than 100 tons). 

### Air Force: 8,250; 220 combat aircraft.

9 Tu-16 medium bombers. 12 II-28 light bombers. 48 Su-7 fighter-bombers. 35 Hunter FGA. 16 T-52 Jet Provost light-strike aircraft. 85 MiG-21 interceptors. 15 MiG-17 fighters. 35 Mi-4, 12 Mi-8 and 9 Wessex helicopters. 2 An-2, 8 An-12, 10 An-24, 2 Tu-124 and 2 Heron transports. Para-Military Forces: 20,000 including 10,000 national guard and 4,000 security troops, form- ing 1 mechanized brigade. 

## ISRAEL 

Population: 3,040,000. Military service (Jewish population only): men, 36 months; women, 20 months. Total armed forces: 75,000 regular cadre and conscripts (can be raised to 300,000 by mobi- lizing reservists within 48-72 hours). Estimated GNP 1970: \$5.4 billion. Defence budget 1971-72: 5,193 million Israeli pounds (\$1,483,700). 3.5 Israeli pounds = \$1. 

### Army: 11,500 regular, 50,000 conscripts (275,000 when fully mobilized). 

4 armoured brigades. 4 infantry brigades. 1 parachute brigade. 300 M-48 (with 105mm guns), 250 Ben Gurion (Centurion with French 105mm gun), 200 Centur- ion, 200 Isherman (with 105mm gun) and Super Sherman, 100 TI-67 (T-54/55 with 105mm gun) and 25 M-60 med tanks; AML-60, 15 AML-90 and some Staghound armd cars; about 1,000 M-2 and M-3 half-tracks; M-113 APCs; 24 M-109 155mm SP howitzers; 155mm howitzers on Sherman chassis; about 300 SP 105mm howitzers, 120mm and 160mm mortars on AMX- chassis; 90mm SP ATK guns and 106mm jeep- mounted recoilless rifles; Cobra, and weapons carrier-mounted SS-10/11 ATGW; 20mm, 30mm and 40mm AA guns. (The MD-660 280-miles-range SSM may become operational during 1971.) RESERVES: would increase above formations to 10 armoured, 9 infantry and 4 parachute brigades.

### Navy 

1 destroyer (used as a training ship). 12 FPB (with Gabriel SSM). 9 motor torpedo boats (less than 100 tons). 8 patrol boats (less than 100 tons). 10 landing craft (4 less than 100 tons). Naval commandos: 500. Navy: 3,500 regular, 1,000 conscripts (8,000 when fully mobilized). 3 submarines. 

### Air Force: 8,000 regular, 1,000 conscripts (17,000 when fully mobilized); 374 combat aircraft.

10 Vautour light bombers. 75 F-4E fighter-bomber/interceptors. 60 Mirage III-C fighter-bomber/interceptors (some with R-530 AAM). 72 A-4E/H fighter-bombers (18 more are due to be delivered during 1971). 27 Mystère IV-A fighter-bombers. 30 Ouragan fighter-bombers. 9 Super Mystère interceptors. 6 RF-4E reconnaissance aircraft. 85 Magister armed trainers. 10 Stratocruiser transports/tankers. 15 Noratlas, 10 C-47 and 4 C-46 transports. 12 Super Frelon, 8 CH-53, 25 AB-205 and 20 Alouette helicopters. 8 SAM batteries with 48 HAWK. Para-Military Forces: 10,000. Militia providing regional border defence units. 

## JORDAN 

Population: 2,225,000. Military service: 2 years. Total armed forces: 60,250. Estimated GNP 1970: \$0.64 billion. Defence budget 1971: 32,300,000 dinars (\$90,440,000). 1 dinar = \$2.8. 

### Army: 58,000.

1 armoured division. 1 mechanized division. 1 infantry division. 1 Royal Guards battalion (armoured). 3 artillery regiments. 1 SAM regiment with Tigercat. 150 M-47 and M-48, and 140 Centurion med tanks; 125 Saladin armd cars; 140 Ferret scout cars; 250 M-113 and 100 Saracen APC; 25 pounder guns, 30 105mm and 155mm howitzers, a few 155mm and 203mm guns; M-42 SP AA guns. 

### Navy: 250. 

8 small patrol craft. 

### Air Force: 2,000; 33 combat aircraft. 

2 ground-attack squadrons with 18 Hunter. 30 1 interceptor squadron with 15 F-104A. 4 C-47 and 2 Dove transports. Helicopters include 7 Alouette III. Para-Military Forces: 37,500, consisting of 7,500 Gendarmerie, and 30,000 National Guard. 


## LIBYA Army: 20,000.

### Army: 52,000. 

4 armoured battalions. 5 infantry battalions. 3 artillery battalions. 2 AA artillery battalions. 6 Centurion-5, 100 T-54/55 and 15 T-34/85 med tanks; Saladin armd cars; Shorland and Ferret scout cars; Saracen APC; 122mm guns, 105mm and 155mm howitzers; L40/70 Bofors AA guns. (An order for 188 Chieftain tanks from Britain is in abeyance.) 


## LEBANON 


Population: 2,775,000. Voluntary military service (proposals have been made to introduce compulsory military training). Total armed forces: 15,250. Estimated GNP 1970: \$1.56 billion. Defence budget 1971: £L166,200,000 (\$51,100,000). Lebanese £3.25 = \$1.

1 motorized battalion. 9 infantry battalions. 40 Charioteer med tanks; 40 AMX-13 and 20 M-41 It tanks; M-706, M-6 and AEC Mark-3 armd cars; M-113 and M-59 APC; 155mm howitzers; 15 M-42 SP AA guns. 2 tank battalions. Navy: 250.

1 patrol vessel. 4 small patrol boats (less than 100 tons). 1 landing craft. Air Force: 1,000; 21 combat aircraft. 12 Hunter FGA.

1 interceptor squadron with Mirage III-C\* with R-530 AAM. 5 transports. 1 helicopter sqn with 4 Alouette II and 6 Alouette III. Some radars of a Crotale SAM system have been delivered. Para-Military Forces: 2,500 Gendarmerie. A National Guard of 5,000 is being formed. Population: 2,000,000. Military service: 18 months. Total armed forces: 22,000. Estimated GNP 1970: \$4.0 billion. Defence budget 1971-72: £L30 million (\$84 million). £L1 = \$2.8. 

### Navy: 1,000.

1 corvette. 3 FPB with SS-12(M) SSM. 1 fleet minesweeper. 2 inshore minesweepers. 1 logistic support ship. 12 small patrol craft. (1 fast frigate is due for delivery during 1971.) Army: 14,000. Population: 16,000,000. Military service: 18 months. Total armed forces: 57,500. Estimated GNP 1970: \$3.34 billion. Defence budget 1971: 491 million dirham (\$97,000,000). 5.06 dirham = \$1. Air Force: 1,000; 7 combat aircraft.

1 interceptor squadron with 7 F-5. 18 Mirage III and 3 T-33 trainers. 8 C-130E and 9 C-47 medium transports. 2 AB-206, 3 OH-13, 4 Alouette III and 6 Super Frelon helicopters. (30 more of the total order of 110 Mirage, and 8 F-5 are due to be delivered during 1972.)

1 armoured brigade. 3 motorized infantry brigades. 1 light security brigade. 1 parachute brigade. 12 independent infantry battalions. 2 camel corps battalions. 3 desert cavalry battalions. 4 artillery groups. 120 T-54 med tanks; 120 AMX-13 It tanks; some EBR-75, and 50 AML-245 and M-8 armd cars; 40 M-3 half-track and 95 Czech APC; 25 Su-100 and AMX-105, and 50 M-56 90mm SP guns; 75mm and 105mm howitzers; 6 Alouette II\|III helicopters. 

## MOROCCO 

Negotiations have taken place for their resale to France, and they are not thought to be operational. 

### Navy: 1,500. 

1 frigate. 31 2 coastal escorts. 1 patrol boat (less than 100 tons). 2 landing ships. 

### Air Force: 4,000; 38 combat aircraft. 

10 F-5A and 4 F-5B interceptors. 24 Magister armed trainers. 45 T-6 and 25 T-28 trainers. 10 C-47 and 11 C-119 transports. OH-13, 24 AB-204, 12 AB-205 and 6 HH-43 helicopters. (12 MiG-17 fighter-bombers are in storage.) 

Para-Military Forces: 23,000. 2,250 Gendarmerie including 2 mobile security battalions; 750 Royal Guards; 20,000 Auxiliaries. 

## SAUDI ARABIA 

Population: 7,400,000. Voluntary military service. Total armed forces: 41,000. Estimated GNP 1970: \$4.1 billion. Defence budget 1970-71: 1,723 million riyals (\$383,000,000). 4.5 riyals = \$1. 

### Army: 35,000. 

4 infantry brigades. 10 SAM batteries with HAWK. 25 M-47 med tanks; 60 M-41 It tanks; 200 AML-60 and AML-90; some Staghound and Greyhound armd cars: Ferret scout cars. DEPLOYMENT: 1,000 in Jordan; 2,000 in UAR. 

### Navy: 1,000.

3 torpedo boats. 1 patrol vessel. 2 FPB. 8 SRN-6 hovercraft. (20 smaller patrol boats are being delivered.) Air Force: 5,000; 75 combat aircraft.

1 fighter-bomber squadron with 15 F-86. 2 ground-attack squadrons with 20 BAC-167. 2 interceptor squadrons with 20 Lightning. 10 C-130E transport aircraft. 4 Alouette III, 1 AB-204, 3 AB-205 and 14 AB-206 helicopters. About 35 Hunter, Lightning and T-33A trainers. 2 SAM regiments with 36 Thunderbird. Para-Military Forces: 30,000. National Guard (formerly known as the 'White Army') - lightly armed tribal levies with Vigilant ATGW. 

## SUDAN 

Population: 16,050,000. Voluntary military service.\* Total armed forces: 37,100. Estimated GNP 1970: \$1.83 billion. Defence budget 1970-71: £\$46,400,000 (\$133,200,000). £Sudan 1 = \$2.87.

### Army: 35,000. 

1 armoured brigade. 6 infantry brigades. 1 independent infantry battalion. 1 parachute regiment. 3 artillery regiments. 1 engineer regiment. 20 T-34/85, 50 T-54 and 50 T-55 med tanks; 50 Saladin and 45 Commando armd cars; 60 Ferret scout cars; BTR-40, BTR-152 and Saracen APC; 55 25-pounder, 40 105mm and some 122mm guns and howitzers; 20 120mm mortars; 80 Bofors 40mm and some Soviet 85mm AA guns. DEPLOYMENT: 2,000 in Egypt. Navy: 600, 6 coastal patrol boats. 2 landing craft.

### Air Force: 1,500; 32 combat aircraft. 

16 MiG-21 interceptors. 5 BAC-145 Mk 5, 8 Jet Provost Mk 52, and 3 Provost Mk 51 light attack aircraft. 3 Pembroke, 3 F-27 Troopship, 6 An-12 and 5 An-24 transports. 10 Mi-8 helicopters. Para-Military Forces: 3,000. 1,000 Gendarmerie; 2,000 Frontier Police. 

## SYRIA 

Population: 6,200,000. Military service: 30 months (Jewish population exempted). Total armed forces: 111,750. Estimated GNP 1970: \$1.46 billion. Estimated defence expenditure 1970: £S670 million (\$176,000,000). £Syrian 3.8 \$1. 

### Army: 100,000.

1 armoured division. 2 mechanized divisions. 2 infantry divisions. \* Proposals for compulsory service have been made, 32

1 parachute battalion. 5 commando battalions. 7 artillery regiments. 8 SAM batteries with SA-2. About 30 JS-3 hy tanks; 150 T-34 and 600 T-54/55 med tanks; some PT-76 It tanks; 100 SU-100 SP guns; 500 BTR-152 APC; 800 Soviet-made guns including 122mm, 130mm and 152mm. 

### Navy: 1,750.

2 minesweepers. 2 coastal patrol vessels. 6 Komar-class patrol boats, with Styx SSM. 12 motor torpedo boats (less than 100 tons). 

### Air Force: 10,000 men; 210 combat aircraft. 

80 MiG-15 and MiG-17 fighter-bombers. 30 Su-7 fighter-bombers. 100 MiG-21 interceptors. 8 Il-14, 6 C-47 transports. 4 Mi-1, 8 Mi-4 and some Mi-8 helicopters. Para-Military Forces: 6,500. 5,000 Gendarmerie; 1,500 Internal Security Camel Corps. 

## TUNISIA 

Population: 5,050,000 Military service: 1 year (selective). Total armed forces: 21,550. Estimated GNP 1970: \$1.24 billion. Estimated defence expenditure 1971: 10,509,000 dinars (\$20,020,000). 1 dinar= \$1.905. 

### Army: 20,000.

1 armoured battalion. 6 infantry battalions. 1 commando battalion. 1 artillery group. 1 Sahara patrol group. About 15 AMX-13 and M-41 It tanks; 20 Saladin and some M-8 armd cars; 105mm SP and 155mm guns; 40mm Bofors AA guns. 

### Navy: 800.

1 corvette. 1 coastal escort. 2 patrol boats with SS-12 (M) SSM. 10 patrol boats (less than 100 tons). (4 FPBs and 6 coastal patrol boats due to be de- livered in 1971.) 

### Air Force: 750; 12 combat aircraft.

12 F-86 fighters. 8 MB-326, 12 T-6 and 14 Saab 91-D trainers. 3 Flamant light transports. 8 Alouette II helicopters. Para-Military Forces: 10,000. 5,000 Gendarmerie organized in 6 battalions. 5,000 National Guard. 

## UNITED ARAB REPUBLIC (UAR)

Population: 34,150,000. Military service: 3 years. Total armed forces: 318,000. Estimated GNP 1970: \$6.43 billion. Defence budget 1971-72: £E 650 million (\$1,495,000,000). £E1 = \$2.3.

### Army: 275,000. 

3 armoured divisions. 4 mechanized infantry divisions. 5 infantry divisions. 2 parachute brigades. 16 artillery brigades. 20 commando battalions. 50 JS-3 and T-10 hy tanks; 1,200 T-54/55 and 250 T-34/85 med tanks; 150 PT-76 It tanks; 850 BTR-40, BTR-50P, BTR-60P, OT-64 and 350 BTR-152 APC; about 150 SU-100 and JSU-152 SP guns; about 1,500 122mm, 130mm and 152mm guns and howitzers, and 40 203mm howitzers: 57mm, 85mm and 100mm ATk guns: Snapper ATGW; 24 FROG-3 and 25 Samlet short-range SSM; ZSU-23-4 and ZSU-57 SP AA guns. 

### Navy: 14,000 including coastguards.

12 submarines (including 6 ex-Soviet W-class and 6 ex-Soviet R-class). 5 destroyers (including 4 ex-Soviet Skory-class). 2 corvettes. 10 submarine chasers. 4 fleet minesweepers. 2 inshore minesweepers. 12 Osa-class and 8 Komar-class patrol boats with Styx SSM. 30 motor torpedo boats (less than 100 tons). 20 landing craft. 

### Air Force: 25,000; 523 combat aircraft.

18 Tu-16 medium bombers. 25 Il-28 light bombers. 200 MiG-21 interceptors. 110 Su-7 fighter-bombers. 200 MiG-17 fighter-bombers. 150 MiG, Yak and L-29 trainers, some can be armed. About 40 Il-14 and 20 An-12 medium transports. 140 Mi-1, Mi-4, Mi-6 and Mi-8 helicopters. Air defence is provided by 37mm, 57mm, 85mm and 100mm guns; up to 70 sites with 6 launchers 33 each of SA-2 SAM; a radar network and six squadrons of MiG-21 interceptors. Co-ordinated with this defence are up to 150 MiG-21J and pos- sibly MiG-23 aircraft - all Soviet-operated. There are also up to 65 Soviet-controlled sites with 4 launchers each of SA-3 (and possibly SA-4). DEPLOYMENT: elements in Sudan. Missile Command: 4,000. This is separate from the Army and the Air Force and its numbers include civilian technicians. Fresh development work may have started on the 1,000 lb warhead 235 mile-range Al Zafir, the 375 mile-range Al Kahir and the 440 mile-range Al Raid, stated to be able to carry a one-ton scientific probe, but these ranges are probably over- optimistic. The first two missiles were designed to be mobile; none is thought to have achieved any operational capability. Para-Military Forces: National Guard - about 120,000.
