# Sub-Saharan Africa 

## Multilateral Agreements 

The Organization of African Unity (OAU), constituted in May 1963, includes all internationally recognized independent African states except South Africa. Its Defence Commission is responsible for defence and security co-operation, and the defence of the sovereignty, territorial integrity and independence of its members. There is a regional defence pact between France, Congo (Brazzaville), the Central African Republic and Chad, and there is a five-party defence agreement between France, Dahomey, Ivory Coast, Niger and Upper Volta which has set up the 'Conseil de défense de l'Afrique équatoriale'. 

## Bilateral Agreements

A number of external powers have military arrangements with countries in the region. The United States has varying types of security assistance agreements and provides significant military aid on either a grant or credit basis to Ethiopia, Liberia and Congo (Kinshasa). For grant military assist- ance purposes, Ethiopia, where the United States has a large communications centre, is considered a base rights country. The Soviet Union and China are not known to have defence agreements with countries in the region but Soviet military assistance has been given to Guinea, Mali and Mauritania. Britain maintains defence agreements with Kenya and Mauritius, and an agreement with South Africa, made in June 1955 and revised in January 1967, covering the use of the Simonstown naval base. France has defence agreements with Cameroun, Gabon, Malagasy Republic, Mauritania, Senegal and Togo; technical military assistance agreements with Cameroun, the Central African Republic, Chad, Congo (Brazzaville), Dahomey, Gabon, Ivory Coast, Malagasy Republic, Mauritania, Niger, Senegal, Togo and Upper Volta; and mutual facilities agreements with Dahomey, Gabon, Ivory Coast, Mauritania and Niger.t 

## CONGO (Kinshasa) (Democratic Republic of the Congo) 

Population: 21,300,000 Voluntary military service. Total armed forces: 46,000. \* With a few important exceptions, only countries with armed forces over 5,000 strong are included. Though in some African States they have a considerable internal security role, civil police forces have not been included. Details of civil police forces of African States and of the armed forces of countries not included here may be found in Adelphi Paper No. 67 The Armed Forces of African States, 1970. The amount of military equipment shown may not necessarily be that which can be used. In some of the developing nations maintenance facilities and skills may pose problems, and spare parts may not be readily available. t Portugal directly assures the defence of Angola, Mozambique and Portuguese Guinea, and Spain of Spanish Sahara, Ceuta and Melilla. All of these are administratively regarded as overseas provinces except Ceuta and Melilla, which are treated as integral parts of Spain. \## Estimated GNP 1970: \$1.9 billion. Estimated defence expenditure 1970: 42 million zaires (\$84,000,000). 1 zaire = \$2. 

### Army: 45,000.

14 infantry battalions. 7 parachute battalions. 1 heavy weapons battalion. 4 other battalions. The above, together with support units, form 7 brigade groups and 1 parachute division. About 80 AML armd cars: M-3 and Ferret scout cars (less than half operational). 

### Navy: 150. 

7 river gunboats. 1 patrol boat. 

### Air Force: 850; 32 combat aircraft. 

17 MB-326GB, 8 T-6G and 5 T-28D armed trainers. 10 C-47, 4 C-54 and 3 C-130 transports. 8 SF-260M trainers. 1 Alouette II, 4 Alouette III and 7 SA-330 Puma helicopters. Para-Military Forces: 6 National Guard and 7 Gendarmerie battalions. 

## ETHIOPIA 

Population: 25,800,000. Voluntary military service. Total armed forces: 42,750. Estimated GNP 1970: US\$1.75 billion. Defence budget 1970-71: E\$89,100,000 (US \$35,640,000). E\$2.5 = US\$1. 

### Army: 39,000.

4 infantry divisions\* (incl Imperial Guard). 1 tank battalion. 1 airborne infantry battalion. 1 armoured car squadron. 4 artillery battalions. 5 air defence batteries. 2 engineer battalions. 55 M-41 med tanks; 15 M-24 It tanks; about 50 APC. 

### Navy: 1,500. 

1 training ship (ex-seaplane tender). 5 patrol boats. 2 motor torpedo boats. 4 gun boats (less than 100 tons). 4 landing craft (less than 100 tons). 

### Air Force: 2,250; 48 combat aircraft.

1 bomber squadron with 4 Canberra B-2. 1 fighter-bomber squadron with 11 F-86F. 1 ground-attack squadron with 13 T-28. 1 ground-attack squadron with 8 Saab-17. 1 fighter squadron with 10 F-5A. 1 reconnaissance squadron with 2 T-33. 1 tpt sqn with 4 C-47, 2 C-54, 4 C-119G, 3 Dove and 1 II-14. 3 trg sqns with 20 Safir, 15 T-28A and 11 T-33. 4 Alouette II and 2 Mi-8 helicopters. Para-military Forces: 13,750. 6,000 Territorial Army - active strength. 6,800 mobile emergency police force; 1,500 frontier guards. 

## GHANA 

Population: 9,050,000. Voluntary military service. Total armed forces: 18,600. Estimated GNP 1970: \$2.57 billion. Defence budget 1970-71: 45,300,000 cedi (\$44,400,000). 1.02 cedi = \$1. 

### Army: 16,500.

2 brigades comprising 7 inf bns and support units. 2 reconnaissance squadrons. Saladin armd cars; Ferret scout cars; heavy mortars. 

### Navy: 1,000.

2 corvettes. 1 coastal minesweeper. 2 inshore minesweepers. 2 seaward defence vessels. 3 P-class patrol boats (less than 100 tons). 

### Air Force: 1,100; no combat aircraft.

1 transport squadron with 7 Otter. 1 transport squadron with 8 Caribou and 3 Heron. 1 comms and liaison squadron with 11 Beaver. 3 Whirlwind, 2 Wessex and 3 Hughes 269 hel. 6 MB-326 and 9 Chipmunk trainers. Para-Military Forces: A workers brigade. 

## GUINEA 

Population: 4,075,000. Military service: 2 years. Estimated GNP 1970: \$0.7 billion. Total armed forces: 5,350. Defence budget 1966-67: 2,338 million Guinea francs (\$9,470,000). 278 Guinea francs = \$1. 

### Army: 5,000. 

5 infantry battalions. 1 armoured battalion. 3 engineer companies. T-34 tks: BTR-152 APC: 105mm and 85mm guns. DEPLOYMENT: about 200 in Sierra Leone. 

### Navy: (Coast Guard) 150. 

6 ex-Soviet patrol boats (less than 100 tons). 

### Air Force: 200; 5 combat aircraft. 

5 MiG-17 fighters. 2 Il-18 and 4 Il-14 transports. Yak-18 and MiG-15 trainers. \* 8,000 men in each. Para-Military Forces: 7,500. 900 Gendarmerie. 1,600 Republican Guard; 5,000 Militia. t There is a substantial shortage of spares for all naval craft. 

## IVORY COAST 

Population: 4,375,000. Military Service: 2 years. Total armed forces: 4,400. Estimated GNP 1970: \$1.44 billion. Estimated defence expenditure 1970: 6,350 million CFA francs (\$22,800,000). 278 CFA francs = \$1. 

### Army: 4,000.

3 infantry battalions. 1 armoured squadron. 1 parachute company. 2 artillery batteries. 1 engineer company. About 5 AMX-13 It tanks: some armd cars, scout cars, 105mm guns, mortars, 40mm AA guns. 

### Navy: 100. 3 patrol vessels (1 less than 100 tons). 

2 landing craft (less than 100 tons). 

### Air Force: 300; no combat aircraft. 

3 C-47 medium, and 1 Mystère 20, 1 Commander 500 and 5 MH-1521 Broussard light transports. 5 Alouette helicopters and 6 light aircraft. Para-Military Forces: 2,000 Gendarmerie. 

## KENYA 

Population: 11,525,000. Voluntary military service. Total armed forces: 7,170. Estimated GNP 1970: \$1.58 billion. Estimated defence expenditure 1970: Sh. 175 mil- lion (\$24,500,000). 7.143 shillings = \$1. 

### Army: 6,300. 

4 infantry battalions. 1 support battalion with a parachute company. Saladin armd cars; Ferret scout cars; 81mm and 120mm mortars; 120mm recoilless rifles. 

### Navy: 250. 1 seaward defence boat. 3 patrol boats.

### Air Force: 620; 6 combat aircraft.

6 BAC-167 ground support aircraft. 1 transport squadron with 4 Caribou. 1 light transport squadron with 7 Beaver. 1 training squadron with 5 Chipmunk and 3 Beaver. 3 Alouette II and 2 H-269 helicopters. (5 Bulldog armed trainers are due to be delivered by mid-1972.)

Para-Military Forces: 1,800 in General Service Units (including Presidential escort). 

## MALAGASY REPUBLIC 

Population: 7,200,000. Military service: 18 months. Total armed forces: 4,100. Estimated GNP 1970: \$0.82 billion. Defence budget 1969: 3,450 million francs (\$13,450,000). 278 MG francs = \$1. 

### Army: 3,700.

2 infantry regiments. 1 parachute company. 1 armoured squadron. 1 artillery battery. 1 engineer regiment. 

### Navy: 200.

1 patrol vessel. 1 training ship. 1 tender. 1 marine company. 

### Air Force: 200; no combat aircraft.

5 C-47 medium and 3 MH-1521 light transports. 2 MD-315 Flamant light aircraft Para-Military Forces: 4,100 Gendarmerie. 

## NIGERIA 

Population: 62,000,000. Voluntary military service. Total armed forces: 252,000. Estimated GNP 1970: \$9.1 billion. Defence budget 1971-72: £N87 million (\$243,600,000). £N1 = \$2.80. 

###Army: 240,000. 3 infantry divisions. 

3 reconnaissance regiments. 3 artillery regiments. Saladin and 20 AML-60/90 armd cars; Ferret scout cars; Saracen APC; 25-pounder, 76mm, 105mm and 122mm guns. 

### Navy: 5,000. 1 frigate (refitting). 3 ex-Soviet FPB (less than 100 tons). 37 6 seaward defence boats. 1 landing craft. (2 corvettes are due to be delivered by mid-1972.) 

### Air Force: 7,000; 32 combat aircraft. 

6 I1-28 medium bombers. 8 MiG-17 fighter-bombers. 8 L-29 Delfin and 10 P-149D armed trainers. Other aircraft include 6 C-47 transports; 20 Do-27/28 communication/liaison aircraft; 8 Whirlwind and Alouette II helicopters.

# RHODESIA

Population: 5,425,000 (250,000 white population). Military service: 12 months (white population). Total armed forces: 4,600. Estimated GNP 1970: \$1.44 billion. Estimated defence expenditure 1970-71: R\$17,879,000 (US\$25,031,000). R\$1 = US\$1.4.

The white population completing military service is assigned for three years part-time training to Territorial units, which include active Territorial battalions based on the cities and reserve Territorial battalions based on country districts. The establishment of the Army Reserves is 8 infantry battalions and one field artillery battery. The majority of ground personnel servicing regular Air Force units are Air Force reservists or non-white civilians employed by the Air Force. Para-Military Forces: 6,400 active; 28,500 reservist. The British South African Police (BSAP) have some military equipment such as small arms and would be responsible for much of the internal security of Rhodesia in the event of civil dis- turbances or a military threat from outside. The RESERVES: 8,000. white population forms only about a third of the active strength, but nearly three-quarters of the Police reserves.

## SENEGAL

Population: 3,950,000. Military service: 2 years. Total armed forces: 5,900. Estimated GNP 1970: \$0.72 billion. Defence budget 1969-70; 4,461 million CFA francs (\$18,060,000). 278 CFA francs = \$1.

### Army: 5,500.

3 infantry battalions. 2 parachute companies. 2 commando companies. 1 reconnaissance squadron. 1 engineer battalion. Support units include a tpt and a sig coy. Greyhound and AML-245 armd cars.

### Navy: 200.

1 coastal escort. 2 submarine chasers. 1 patrol boat (less than 100 tons). 

### Air Force: 200; no combat aircraft.

4 C-47 medium and 4 MH-1521 light transports. 2 Bell-47G helicopters. Para-Military Forces: 1,600 Gendarmerie. 

Population: 2,900,000. Voluntary military service. Total armed forces: 15,000. Estimated GNP 1970: \$0.18 billion. Defence budget 1969: 64,320,000 shillings (\$9,005,000). 7.143 Somali shillings = \$1. 

4 tank battalions. 9 mechanized infantry battalions. 1 commando battalion. About 150 T-34 med tanks*; 5 Ferret scout cars; over 200 BTR-40, 50 and 152 APC; 100mm guns. \## SOMALI DEMOCRATIC REPUBLIC Navy: 250. 6 patrol boats (less than 100 tons). \## Army: 13,000. Air Force: 1,750; 20 combat aircraft. 20 MiG-15/MiG-17 fighters.* Only about one quarter are serviceable. 38 2 MiG-15/MiG-17 UTI and 3 P-18 trainers. Tpts include 1 C-45, 3 C-47, 3 An-2 and 1 An-24. Para-Military Forces: 500 border guards. 

## SOUTH AFRICA 

Population: 20,550,000 (3,900,000 white popula- tion). Military service: 9-12 months in Citizen Force. Total armed forces: 44,250. Estimated GNP 1970: \$17.6 billion. Defence budget 1971-72: 316 million rand (\$442,400,000). 1 rand = \$1.4. 

### Army: 32,000 (10,000 regular; 22,000 Citizen Force) 

100 Centurion Mark 5, 100 Sherman and 40 Comet med tanks; 500 AML-60 and AML-90, and 50 M-3 armd. cars; 200 Ferret scout cars; Saracen APC. RESERVES: 23,000 trained reserves in Citizen Force. 

### Navy: 4,250 (3,000 regular: 1,250 Citizen Force). 

1 submarine (2 more due for delivery by mid-1972).

2 destroyers with Wasp ASW helicopters.\* 6 ASW frigates. 1 escort minesweeper. 10 coastal minesweepers. 5 seaward defence boats. 1 fleet replenishment tanker. RESERVES: 4,750 trained reserves in Citizen Force. 

### Air Force: 8,000 (5,000 regular: 3,000 Citizen Force); 163 combat aircraft.

1 bomber squadron with 16 Canberra B-12. 1 It bomber squadron with 15 Buccaneer Mark 50. 1 fighter-bomber squadron with 20 Mirage III-EZ (with AS-20 and AS-30 ASM).t 1 interceptor sqn with 16 Mirage III-CZ (with R-530 AAM). Other aircraft include 4 Mirage III-RZ, 30 F-86, 5 Vampire FB-5 and at least 50 MB-326 Impala. 1 maritime recce squadron with 7 Shackleton. 9 Transall, 30 C-47, 4 C-54, 7 C-130B/E and 1 Viscount med and 9 P-166 light transports. 106 Alouette II\|III, 8 Wasp and 16 Super Frelon helicopters. (Deliveries of 20 SA-330 Puma have begun.) A Cactus air defence missile system is being in- \* Reports suggest that both destroyers and 1 frigate are temporarily in reserve. t Mirage aircraft are to be built in South Africa under licence. stalled, but the Crotale SAM have not yet been delivered. RESERVES: The Citizen Air Force operates eight squadrons with 50 Impala, about 120 Harvard armed trainers and C-47 transports.

Para-Military Forces: 78,000. 75,000 Kommandos organized and trained on the same lines as the Citizen Force. 3,000 police with anti-terrorist training whose equipment includes 80 Saracen APC on loan from the army. 

## TANZANIA 

Population: 13,600,000. Voluntary military service. Total armed forces: 11,100. Estimated GNP 1970: \$1.1 billion. Defence budget 1968-69: 190,300,000 shillings (\$26,640,000). 7.143 shillings = \$1. 

### Army: 10,000 4 infantry battalions. 

14 Chinese T-62 It tanks; some BTR-40 and 152 APC; Soviet field artillery and Chinese mortars. 

### Navy: 600. 

5 fast patrol boats. 8 patrol boats (less than 100 tons). 

### Air Force: 500; no combat aircraft. 

1 An-2, 6 Beaver, and 4 Caribou transports. 7 P-149 trainers. Para-Military Forces: A police marine unit. 

## UGANDA 

Population: 10,025,000. Voluntary military service Total armed forces: 9,000. Estimated GNP 1970: \$1.06 billion. Defence budget 1968-69: 120,540,000 shillings (\$16,875,000). 7.143 shillings= \$1. 

### Army: 8,550

2 brigades each of 2 infantry battalions with supporting services. 2 border guard battalions. 1 mechanized battalion. 1 parachute/commando battalion. 1 artillery regiment. 5 M-4 med tanks; 16 Ferret scout cars; 20 BTR-40 and BTR-152, and 12 OT-64B APC (perhaps half are operational). 

### Air Force: 450; 19 combat aircraft.

1 fighter squadron with 7 MiG-15 and MiG-17. 12 Magister armed trainers. 1 transport squadron with 6 C-47 and 1 Caribou. 2 AB-206 and 2 Scout helicopters. 4 Piaggio P-149 and 12 L-29 Delfin trainers, and 7 Piper light aircraft. 

## ZAMBIA 

Population: 4,250,000. Voluntary military service. Total armed forces: 5,500. Estimated GNP 1970: \$1.58 billion. Defence budget 1966: 12,600,000 kwachas (\$17,640,000). 1 kwacha = \$1.4. 

### Army: 4,500.

1 brigade of 3 inf bns and 1 recce sqn. 1 artillery battery. 1 engineer squadron. A signals squadron and supporting services. Ferret scout cars; 105mm guns. 

### Air Force: 1,000; 12 combat aircraft.

4 Jastreb light attack aircraft. 8 SF-260MZ armed trainers. 1 transport squadron with 2 C-47 and 4 Caribou. 1 comms/liaison sqn with 6 Beaver and 2 Pembroke. 4 AB-205 helicopters. 2 Galeb and 6 Chipmunk trainers. (12 MB-326 ground-attack aircraft are on order.) Para-Military Forces: 2 police mobile battalions. 
