# Asia and Australasia

## CHINA 

China's dominant strategic concept is People's War, in which most of the population is allotted a military role. This entails a peacetime programme of rudimentary military training for civilians. The People's Liberation Army (PLA) is heavily involved in the political and military administration of the country. China's large manpower pool allows great selectivity in manning the 2.9 million strong regular forces. The vast bulk of the manpower lies in the land forces, specifically in the infantry and artillery. Out of a total of 140 divisions, only 5 are armoured. The Navy and Air Force account for little more than 10 per cent of the personnel, compared with about 30 per cent in the Soviet Union. The PLA is not equipped on the scale of major industrial countries, including the Soviet Union, and its mobility is limited. However, China's military production is improving steadily in quantity and quality. She now produces the Tu-16 medium bomber, the MiG-21, the T-59 medium tank, the (Chinese) T-62 light tank, and APC, which improve the mobility of the PLA; also a new Chinese twin-engined fighter is being developed. In the Navy, the build-up of fast guided-missile patrol boats is continuing, along with its own version of the R-class medium range diesel-powered submarine. At least one nuclear-powered submarine appears to be under construction; it is probably an attack vessel. The PLA is organized in 11 Military Regions, and to some extent its equipment and logistics support reflect this regional character. Its deployment is uneven, with major concentrations along the littoral, the Canton-Wuhan railway and in the north-east. During 1969-70, there were some shifts of forces from the south of China to the northern half of the country, but little movement has been reported since. In July 1971 there were thought to be 15,000-20,000 railway engineers, con- struction engineers and protecting troops in North Vietnam and Laos. China has a 30-year Treaty of Alliance and Friendship with the Soviet Union signed in 1950 with mutual defence obligations, the validity of which must be in doubt. China has a mutual defence agreement with North Korea dating from 1961, and it is probable that she has well-defined defence commitments towards North Vietnam. China has in the past year continued to provide military assistance to Pakistan and Tanzania and to Albania with whom she has been co-operating on defence matters. 

### Nuclear weapons programme 

China conducted only one nuclear test in the past year, the eleventh since 1964. As with at least three of the previous tests, the 1970 explosion involved a fusion (thermonuclear) device with a yield of some 3 megatons. China has significant resources of natural uranium and its own plant for uranium enrichment. It may now have sufficient fissionable material for a total of about 120 fission and fusion weapons, although the availability of deuterium and/or tritium may constrain produc- tion of fusion weapons. For air delivery of nuclear weapons China had until recently only a few old Tu-4 bombers. At least 30 Tu-16, a medium bomber with an operational range of about 1,500 miles, have now been produced, and estimated production capacity is some 5 a month. China, which has been testing MRBM since the mid-1960s, has apparently deployed, mainly in north-western and north-eastern China, about 20 operational missiles with a range of up to 1,000 miles.\* During 1970-71, a new missile testing site was also brought into use in Manchuria, The 230-kilogramme second earth satellite was launched, in March 1971, by a booster of IRBM capability. 41 allowing ballistic flights of up to 2,000 miles into the Sinkiang desert. One test from this site in late 1970 may have been connected with the development of an IRBM, or components for an ICBM. Full-range testing of an ICBM would require the use of impact areas and tracking facilities in the Indian or Pacific Oceans. There is no clear evidence to show what 'mix' of missile forces China is seeking to develop. The design of any Chinese ICBM would have to take into account the fact that the urban areas on the north-western coast of the United States are some 6,000 miles from Chinese territory. The responsibility for operational Chinese missile forces is believed to have been assigned to the 'Second Artillery Command'. It is not clear whether this Command is autonomous (cf. the Soviet Strategic Rocket Forces) or is subordinate to the Army. 

## CHINA 

Population: 760,000,000.

DEPLOYMENT: China is now divided into 11 Military Regions (MR), as Inner Mongolia has been incorporated in the Peking MR, and Tibet in the Chengtu MR. The military commander of each Region commands the regular air and naval forces assigned to it, and the civilian militia. The MR are in turn divided into Military Districts (MD), with usually two or three Districts to a Region. It is believed that basically one Army is assigned to each MD giving a total of about 30 Armies. An Army generally consists of three infantry divisions, three artillery regiments and, in some cases, three armoured regiments. Of the five armoured divisions in the PLA, two or three are probably kept in the Peking and Shenyang Regions. The geographical distribution of the divisions (excluding artillery) is believed to be: North and northeast China (Shenyang and Peking MR): 33 divisions. East and southeast China (Tsinan, Nanking and Foochow MR): 25 divisions. South-central China (Canton\|\| and Wuhan MR): 31 divisions. Midwest China (Lanchow MR): 11 divisions. West and southwest China (Sinkiang, Chengtu and Kunming MR): 20 divisions. North Vietnam and Laos: 1 railway engineer division and some construction engineer troops, in all 15-20,000 men. The army is, however, adequately equipped with infantry weapons, mortars, rocket-launchers, recoilless rifles and light and medium artillery, all produced in China. § There are, in addition, two or three divisions of border troops in each of these MR. II Includes Hainan island. 


### Navy: 150,000 (including Naval Air Force and 28,000 Marines).

1 submarine, G-class (with ballistic missile tubes). 32 fleet submarines. t 3 coastal submarines. 4 destroyers. 4 destroyer escorts. 11 patrol escorts. 24 submarine chasers. 15 missile patrol boats. 30 minesweepers. 45 auxiliary minesweepers. 220 MTB and hydrofoils (less than 100 tons). 320 motor gunboats Many less than 530 landing ships/landing craft 100 tons. 

DEPLOYMENT: North Sea Fleet: 240 vessels. The main bases are at Tsingtao and Lushun. It is deployed along the coast from the mouth of the Yalu river in the north to Lienyunkang in the south. East Sea Fleet: 700 vessels. Bases are at Shanghai and Chou Shan. It is deployed along the coast from Lienyunkang in the north to Chaoan Wan in the south. South Sea Fleet: 300 vessels. Bases are at Huangpu and Chanchiang. It is deployed from Chaoan Wan in the north to the North Vietnamese frontier in the south. China is not known to have any missiles for this boat. t Also about 10 older, training vessels. NAVAL AIR FORCE: 16,000; about 450 shore-based combat aircraft, including up to 100 Il-28 torpedo-carrying light bombers and substantial numbers of MiG-15 and MiG-17 fighters: Though under Navy command, the fighters are fully integrated into the air defence system. 

### Air Force: 180,000 (incl 85,000 air-defence person- nel); about 2,800 combat aircraft. 

About 30 Tu-16 and a few Tu-4 medium bombers. 150 Il-28 light bombers. About 1,700 MiG-15 and MiG-17; up to 800 MiG-19 and a growing number of MiG-21 fighters. Some An-2, II-14 and II-18 transports and Mi-4 helicopters (these could be supplemented by about 350 aircraft of the Civil Air Bureau). There is an air-defence system, initially developed to defend the eastern seaboard of China and now greatly expanded, based on early warning/con- trol radar, interceptor aircraft and some SA-2 SAM. 

### Para-Military Forces: 

About 300,000 security and border troops, includ- ing 19 infantry-type divisions and 30 independent regiments stationed in the frontier areas; the public security force and a civilian militia with an effective element of probably not more than 5 million; production and construction corps in a number of MR, including those adjoining the northern frontier. 

## OTHER ASIAN COUNTRIES AND AUSTRALASIA 

### Multilateral Agreements 

In 1954 the United States, Australia, Britain, France, New Zealand, Pakistan, the Philippines and Thailand signed the South-East Asia Collective Defence Treaty, which came into force in 1955 and brought into being SEATO. They committed themselves to consult with a view to joint defence in the event of direct or indirect aggression against a member country or against the so-called 'protocol states' of Cambodia, Laos and South Vietnam. However, since 1955 and 1956 respectively, Cambodia and Laos have not accepted the protection of SEATO. The treaty area is the general area of South-East Asia and the South-West Pacific, below latitude 21° 30' North. SEATO has no central command structure and forces remain under national control. In 1969 Britain ceased to declare ground forces to the contingency plans for the Organization and France has no forces declared. Pakistan has announced her progressive disengagement from the Alliance. All remain members. The United States, Australia, New Zealand and Thailand have troops serving in South Vietnam. This intervention was not the result of a decision by the SEATO Council, but these countries have, for the most part, justified this action in terms of their SEATO obligations. Australia, New Zealand and the United States are the members of a tripartite treaty known as ANZUS, which was signed in 1951 and is of indefinite duration. Under this treaty each agrees to 'act to meet the common danger' in the event of armed attack on either metropolitan or island territory of any one of them, or on armed forces, public vessels or aircraft in the Pacific. Australia, Malaysia, New Zealand, Singapore and Britain have agreed Five-Power defence arrangements relating to the external defence of Malaysia and Singapore, which will come into effect on 1 November 1971. Britain, Australia and New Zealand maintain forces in Malaysia and Singapore, with the land and naval components based in Singapore and Australia's air contri- bution mainly at Butterworth in the Malayan Peninsula. Until 1 November 1971, the British commitment is governed by the Anglo-Malaysian Defence Agreement but this is to be replaced after that date by new Five-Power political arrangements. These arrangements envisage that in the event of any armed attack or threat of attack externally organized or supported against Malaysia or Singapore, the five governments would consult together for the purpose of deciding what measures should be taken, jointly or separately. 

## Bilateral Agreements 

The United States has bilateral defence treaties with Japan,* the Republic of China, the Republic of Korea and the Philippines. It has a number of military arrangements with other countries of the region. It provides significant military aid on either a grant or credit basis to the Republic of China, Cambodia, India, Indonesia, the Republic of Korea, Laos, Malaysia, Pakistan, Singapore, Thailand and South Vietnam. It sells military equipment to many countries, notably Australia, the Republic of China and Japan. For grant military assistance purposes, Cambodia, the Republic of Korea and the Republic of China are considered forward defence areas. Laos, Cambodia, Thailand and South Vietnam receive grant military assistance direct from the US Department of Defense budget, the only countries in the world to do so. There are military facilities agreements with Australia, Japan, the Republic of Korea and the Philippines. Major bases maintained in the region include Okinawa and Guam. The Soviet Union has treaties of friendship, co-operation and mutual assistance with Mongolia and the Democratic People's Republic of Korea. The validity of a similar treaty with the People's \* Either party may terminate the treaty by giving 1 year's notice to the other. 44 Republic of China must be in doubt. Military assistance agreements with Ceylon and the People's Democratic Republic of Vietnam reportedly exist. Important Soviet military aid is also given to Afghanistan and India and, on a small scale, to Pakistan.\* China has non-aggression treaties with Burma, Afghanistan, and Cambodia, a treaty of friend- ship, co-operation and mutual assistance with North Korea; and a treaty of friendship with North Vietnam, which is thought to contain defence arrangements. 

## AFGHANISTAN 

Population: 17,600,000. Military service: 2 years. Total armed forces: 83,000. Estimated GNP 1970: \$1.4 billion. Estimated defence expenditure 1970: 1,400 million afghanis (\$31,100,000). 45 afghanis = \$1. 

### Army: 80,000.

1 armoured division. 2 infantry divisions. 1 infantry brigade (Royal Bodyguard). 10 independent motorized battalions. 10 independent infantry battalions. T-34 and T-54 medium tanks and Snapper ATGW. 

### Air Force: 3,000; 100 combat aircraft.

3 light bomber squadrons with II-28. 2 interceptor squadrons with 30 MiG-21. 1 interceptor squadron with 12 MiG-19. 4 fighter-bomber squadrons with MiG-15/17. 1 II-18, 25 Il-14, 10 An-2, 2 Twin Otter and 5 Anson transports. Mi-1 and Mi-4 helicopters. Para-Military Forces: 13,000 Gendarmerie. 

## AUSTRALIA 

Population: 12,775,000. Two years' selective military service. Total armed forces: 88,280. Estimated GNP 1970: \$US 34.4 billion. Defence budget 1970-71: $A1,149 million ($US1,261,120,000). \$A1 = \$US1.12. 

### Army: 47,760. 

1 tank regiment. 1 cavalry regiment. 9 infantry battalions. 2 battalions of the Pacific Islands Regiment (PIR) 1 Special Air Service (SAS) regiment. \* On 9 August 1971 the Soviet Union and India signed a 20-year Treaty of Peace, Friendship and Co-opera- tion in which each undertook to come to the assistance of the other in the event of a conflict with a third country. 4 field artillery regiments. 1 light anti-aircraft regiment. 1 aviation regiment. 5 signals regiments. 1 Logistic Support Force. 140 Centurion med tanks; 265 Ferret scout cars; 675 M-113 APC; 235 105mm howitzers; about 50 Sioux and Alouette III helicopters; 25 light aircraft. DEPLOYMENT: A task force of 7,000 in South Vietnam (including 2 inf bns and supporting services);f 1 bn gp and 1 sig regt in Singapore; 2 PIR bns in Papua-New Guinea. RESERVES: The Citizen Military Force of 36,000 is intended to form 24 infantry battalions with supporting arms and services. 

### Navy: 17,820.

4 submarines. 1 aircraft carrier (ASW). 3 GM destroyers with Tartar SAM. 5 destroyers. 6 destroyer escorts. 2 minehunters. 4 coastal minesweepers. 20 patrol boats. 1 fast troop transport. 1 destroyer tender. Carrier-borne aircraft include:- 1 fighter-bomber squadron with A-4G Skyhawk, 1 ASW squadron with S-2E Tracker and 1 heli- copter squadron with Wessex. RESERVES: Navy Citizen Military Force; 4,330. 

### Air Force: 22,700; 210 combat aircraft.

1 bomber squadron with Canberra B-20. 2 fighter squadrons with F-4E. 4 interceptor/strike squadrons with Mirage III-O, 1 MR squadron with 10 P-3B Orion and 1 MR squadron of 12 P-2H Neptune. 64 MB-326 trainers. t Announced withdrawals will reduce this figure to 6,000 by the end of 1971. 45 24 C-130, 10 HS-748, 24 Caribou, 22 C-47 tpts. 2 helicopter squadrons with Iroquois. DEPLOYMENT: 2 Mirage sqns in Malaysia/Singapore; 1 hel sqn in Vietnam. RESERVES: 950 Citizen Air Force. 

## BURMA 

Population: 28,175,000. Military service: 2 years. Total armed forces: 143,500. Estimated GNP 1970: \$3.2 billion. Defence budget 1970-71: 480 million Kyat (\$100,600,000). 4.77 kyat= \$1. 

### Army: 130,000. 

5 regional commands. 3 infantry divisions. The army is largely an infantry force, with some artillery, engineer and signals regiments. It is organized chiefly for counter-insurgency and internal security duties. Comet med tanks; Humber armd cars; Ferret scout cars; mainly American, British and Yugo- slav light arms. 

### Navy: 7,000. 

1 frigate. 1 escort minesweeper. 2 coastal escorts. 5 motor torpedo boats (less than 100 tons). 34 river and patrol gunboats. 7 motor gunboats (less than 100 tons). 40 landing craft (less than 100 tons). 

### Air Force: 6,500; 18 combat aircraft. 

12 AT-33 and 6 Vampire armed trainers. 4 C-45, 12 C-47, 8 Otter and 2 Bristol 170 tpts. 6 Sioux, 10 Huskie, 8 Alouette III and 10 Shawnee helicopters. Para-Military Forces: 25,000. 

## CAMBODIA 

Population: 7,000,000. Voluntary military service.\* Estimated GNP 1970: \$0.91 billion. Total armed forces: 179,000. Defence budget 1971: 18,650 million riels (\$336,000,000). 55.5 riels = \$1. 

### Army: 175,000.

200 infantry and commando battalions. 1 tank regiment. 1 armoured car battalion. 3 parachute battalions. M-24 and AMX-13 It tks: M-8 and M-20 armd cars; M-3 scout cars; BTR-152 APC; 105mm howitzers and Soviet 76mm and 122mm guns; 40mm, 57mm, 85mm and 100mm AA guns. 

### Navy 1,600 (including 150 marines).

2 patrol vessels. 2 support gunboats. 2 motor torpedo boats (less than 100 tons). 6 patrol boats (less than 100 tons). 4 landing craft. Air Force: 2,400; 7 combat aircraft. 7 T-28 Trojan ground-attack aircraft. 5 C-47, 5 An-2, and 1 Il-14 transports. 3 MiG-15 UTI, 11 Horizon and 4 Yak-18 trainers. 4 Alouette II, 1 Mi-4 and 2 H-34 helicopters. Para-Military Forces: 150,000. 

## REPUBLIC OF CHINA (TAIWAN) 

Population: 14,575,000. Military service: Army 2 years; Navy and Air Force 3 years. Estimated GNP 1970: \$5.5 billion. Total armed forces: 540,000. Estimated defence expenditure 1971: 24,500 million new Taiwan dollars (\$601,250,000). 

### Army: 390,000.

2 armoured divisions. 14 infantry divisions. 6 light divisions. 3 armoured cavalry regiments. 1 SAM battalion with HAWK. 1 SAM bn and 1 SAM bty with Nike-Hercules. 2 airborne brigades. 4 Special Forces Groups. M-47 and M-48 med tks; M-24, and M-41 It tks; M-18 tk destroyers. DEPLOYMENT: 60,000 on Quemoy; 20,000 on Matsu. \* Conscription is authorized but not yet in force. 
### Navy: 35,000. 

10 destroyers. 6 destroyer escorts. 12 frigates. 12 submarine chasers. 

12 patrol vessels. 3 fleet minesweepers. 15 coastal minesweepers. 2 inshore minesweepers. 21 tank landing ships. 9 medium landing ships. 30 landing craft. Marine Corps: 35,000. 2 divisions. 

### Air Force: 80,000; 385 combat aircraft. 

80 F-100A/D fighter-bombers. 70 F-5A tactical fighters. 45 F-104G interceptors. 150 F-86F interceptors. 8 RF-104G and 4 RF-101 recce aircraft. About 95 C-46, C-47 and C-119 transports. 10 UH-19 helicopters. Population: 557,000,000. Voluntary military service. Total armed forces: 980,000. Estimated GNP 1970: \$49 billion. Defence budget 1971-72: 12,420 million rupees (\$1,656 million). 7.5 rupees= \$1. 

### Army: 860,000.

1 armoured division. 2 independent armoured brigades. 13 infantry divisions. 10 mountain divisions. 6 independent infantry brigades. 2 parachute brigades. About 20 AA artillery units. 200 Centurian Mk 5/7, 250 Sherman, 450 T-54 and T-55 and 300 Vijayanta med tanks; 150 PT-76 and 100 AMX-13 It tanks; OT-62 and Mk. 2/4A APC; about 3,000 artillery pieces, mostly 25-pounders, but including about 350 100mm and 140 130mm guns; SS-11 and Entac ATGW. 

### Navy: 40,000.

1 16,000-ton aircraft carrier. 4 submarines (ex-Soviet F-class). 2 cruisers. 3 destroyers. 9 destroyer escorts (including 5 ex-Soviet Petya class). 1 general purpose frigate. 5 anti-submarine frigates. 3 anti-aircraft frigates. 10 patrol boats (4 less than 100 tons).

4 coastal minesweepers. 4 inshore minesweepers. 1 landing ship. 2 landing craft. 9 seaward defence boats (6 less than 100 tons). The naval air forces includes 35 Sea Hawk attack aircraft, 12 Alizé maritime patrollers, and 2 Sea King and 10 Alouette III helicopters. 10 Sea Hawks, 5 Alizés and 2 Alouettes can be carried on the aircraft carrier at any one time. 

### Air Force: 80,000; 625 combat aircraft.

3 light bomber squadrons with Canberra B (1). 5 fighter-bomber squadrons with Su-7. 2 fighter-bomber squadrons with HF-24 Marut 1A. 6 fighter-bomber squadrons with Hunter F-56. 2 fighter-bomber squadrons with Mystère-IV. 7 interceptor squadrons with MiG-21. 8 interceptor squadrons with Gnat. 1 reconnaissance squadron with Canberra PR-57. 1 maritime recce sqn with L-1049 Super Constella- tion. (8 to 25 aircraft in a combat squadron). Transports include about 55 C-47, 60 C-119, 20 II-14, 30 An-12, 25 Otter, 12 HS-748 and 15 Caribou. 

## INDIA 

Population: 114,500,000. Selective military service. Total armed forces: 319,000. Estimated GNP 1970: \$11.6 billion. Estimated defence expenditure 1970: 103 billion rupiahs (\$272,000,000). 378 rupiahs = \$1. Helicopters include about 80 Mi-4, 150 Alouette III, 10 Bell-47 and a few Mi-8. About 50 SA-2 SAM complexes. 

### Army: 250,000. 

15 infantry brigades, formed from about 100 infantry battalions. 8 armoured battalions. 1 paracommando regiment (RPKAD). The KOSTRAD (Strategic Reserve Command) consists of about six bdes and includes paratroops and armour, artillery and engineers. About one-third of the army is engaged in civil and administrative duties. Stuart, AMX-13 and PT-76 light tanks; Saladin armd cars; Ferret scout cars; Saracen and BTR- 152 APC; artillery includes Soviet 57mm AA guns and associated radar. Para-Military Forces: About 100,000 in Border Security Force. 

### Navy:\* 34,000 (incl 14,000 Marines). 

12 submarines (ex-Soviet W-class).

1 cruiser (ex-Soviet Sverdlov-class). 4 destroyers (ex-Soviet Skory-class). 11 frigates (including 7 ex-Soviet Riga-class). 18 coastal escorts (14 ex-Soviet, 4 ex-USA). 12 Komar-class patrol boats with Styx SSM. 8 patrol boats. 30 motor torpedo boats. 6 fleet minesweepers. 15 coastal minesweepers. 18 motor gunboats. 25 seaward defence boats (less than 100 tons). 6 landing ships. 7 landing craft. The Marines form two brigades. Naval Air Arm 20 MiG-19 and MiG-21 interceptors. 5 HU-16 and PBY-5A ASW aircraft. About 12 S-55, S-58 and Mi-4 helicopters. 

### Air Force: 35,000; 122 combat aircraft t.

22 Tu-16 bombers, some with Kennel ASM. 10 II-28 light bombers. 5 B-25 light bombers. 10 F-51D light-strike aircraft. About 20 MiG-15, 40 MiG-17 and 15 MiG-21 interceptors (mostly in storage). About 60 transports, including II-14, C-130B, C-47, An-12 and Skyvan. About 30 helicopters, including Mi-4, Mi-6, Alouette II and Bell-204. At least 3 SA-2 sites. Para-Military Forces: A police Mobile Brigade of about 20,000. About 100,000 Militia. 

## JAPAN 

Population: 104,600,000. Voluntary military service. Total armed forces: 259,000. Estimated GNP 1970: \$195 billion. Defence budget 1971-72: 670,900 million yen (\$1,864 million). 360 yen = \$1. 

### Army: 179,000. 

1 mechanized division. 12 infantry divisions (7,000-9,000 men each). 1 airborne brigade. 1 artillery brigade. 1 signal and 5 engineer brigades. 1 helicopter brigade. 3 SAM groups with HAWK. \* It is thought that only about one-third of the Navy is operational. t Only about 80 aircraft are thought to be fully opera- tional. 380 Type 61 and 120 M-4 med tanks; M-24 and 140 M-41 It tanks; Type 60 APC; 30 M-52 105mm and 10 M-44 155mm SP howitzers; 203mm howitzers; Type 60 twin 106mm SP recoilless rifles; Type 64 ATGW; 120 aircraft and 220 helicopters. RESERVES: 36,000. 

### Navy: 38,300.

11 submarines. 1 GM destroyer with Tartar SAM. 37 ASW destroyers. 1 frigate. 20 submarine chasers. 5 motor torpedo boats (2 less than 100 tons). 2 minelayers. 37 coastal minesweepers. 3 tank landing ships. 1 medium landing ship. 6 landing craft. 42 small landing craft (less than 100 tons). Naval air component: 140 combat aircraft.

4 maritime recce sqn with 2 PS-1, 60 P-2J and P2V-7. 3 maritime recce sqn with 55 S2F-1. 3 helicopter squadrons with HSS-2 and HSS-1N. 

### Air Force: 41,700; 375 combat aircraft.

7 fighter-bomber squadrons with F-86F. 7 interceptor squadrons with F-104J. 1 reconnaissance squadron with RF-86F. (Deliveries of F-4EJ are due to begin during 1971.) (18-25 aircraft in a combat squadron.) 3 transport squadrons with 30 C-46 and 10 YS-11. 20 helicopters incl S-62 and V-107. 360 trainers incl T-1, T-33, T-34 and F-104 DJ. 4 SAM bns with Nike-Hercules (100 launchers). A Base Air Defence Ground Environment with 24 control and warning units. 

## KOREA--DEMOCRATIC PEOPLE'S REPUBLIC (NORTH)

Population: 13,975,000. Military service: Army 3 years, Navy and Air Force 4 years. Total armed forces: 401,000. Defence budget 1971: 2,183 million won (\$849,400,000). 2.57 won = \$1. 48

### Army: 360,000. 

2 armoured divisions. 20 infantry divisions. 5 independent infantry brigades. 15,000 men in 'special commando teams'. 750 T-34 and T-54 med tanks; PT-76 It tanks; 950 BA-64, BTR-40 and BTR-152 APC; 200 SU-76, SU-100 and ZSU-57 SP guns; 2,000 AA guns; 6,000 other guns and mortars up to 152mm calibre; about 30 SA-2 SAM sites (about 180 launchers). 

### Navy: 11,000.

3 submarines (ex-Soviet W-class). 6 Komar- and 9 Osa-class FPB with Styx SSM. 3 torpedo boats. 40 high speed torpedo boats (less than 100 tons). 10 fleet minesweepers. 22 patrol vessels (4 less than 100 tons). 11 motor gunboats. 

### Air Force: 30,000; 555 combat aircraft. 

70 II-28 light bombers. 380 MiG-15 and MiG-17 fighter-bombers. 100 MiG-21 interceptors. 5 MiG-19 interceptors. About 40 An-2, Li-2,.II-12 and II-14 transports. 20 Mi-4 helicopters. 70 Yak-11, Yak-18, MiG-15 and II-28 trainers. Para-Military Forces: 25,000 security forces and border guards; a civilian militia with a claimed strength of 1,250,000. 

## KOREA-REPUBLIC OF KOREA (SOUTH) 

Population: 32,700,000. Military service: Army/Marines, 2 years; Navy/ Air Force, 3 years. Total armed forces: 634,250. Estimated GNP 1970: \$8.3 billion. Estimated defence expenditure 1971: 129,000 million won (\$411,000,000). 314 won = \$1. 

### Army: 560,000. 

29 infantry divisions (10 in cadre only). 2 armoured brigades. 80 artillery battalions. 1 SSM battalion with Honest John. 2 SAM bns with HAWK and 1 with Nike-Hercules. M-4 and M-48 med tanks; Stuart and M-24 It tanks; M-10 and M-36 tank destroyers; M-8 armd cars and M-113 APC; guns up to 155mm. \## DEPLOYMENT 2 infantry divisions and some engineer units are in South Vietnam. 

### Navy: 16,750.

3 destroyers. 3 destroyer escorts. 4 frigates. 6 escort transports. 11 coastal escorts. 17 patrol boats. 12 coastal minesweepers. 20 landing ships. Marine Corps: 33,000. 5 brigades. DEPLOYMENT: 1 brigade in South Vietnam. 

### Air Force: 24,500; 235 combat aircraft. 

18 F-4 fighter-bombers. 110 F-86F fighter-bombers. 77 F-5 tactical fighters. 20 F-86D AWX (with Sidewinder AAM). 10 RF-86F reconnaissance aircraft. 35 transports including C-46, C-47 and C-54. Helicopters include 6 H-19. Para-Military Forces: A local defence militia with a strength of 1 to 2 million is being formed. LAOS Population: 3,030,000. Estimated GNP 1970: \$0.2 billion. 500 kip = \$1. 1. ROYAL LAO FORCES Military service: conscription. Total strength: 55,000. Estimated defence expenditure: 10,800 million kip (\$21,600,000). 

### Army: 52,600. 58 infantry battalions. 

1 artillery regt of 4 bts. M-24 and PT-76 It tanks; M-8 armd cars; M-3 scout cars; BTR-40 and M-113 APC; 85mm guns and 75mm, 105mm and 150mm howitzers. 

### Navy: about 400. 

4 river squadrons consisting of: 36 patrol craft and lighters, 10 landing craft (all under 100 tons, most not operational).

### Air Force: 2,000; 75 combat aircraft. 

49 About 75 T-28 light-strike aircraft. 20 C-47 and AC-47 transports and gunships. About 8 helicopters. Para-Military Forces and irregulars: 36,000.

2.  PATHET-LAO FORCES: Total strength about 45,000 men (incl dissident neutralists). PT-76 It tanks; BTR-40 armd cars; 105mm howitzers. The Pathet-Lao are believed to be integrated with about 75,000 regular North Vietnamese combat and logistics troops, and have received arms and ammunition of Soviet and Chinese origin. The Pathet-Lao and North Vietnamese control all the eastern half of Laos. 

## MALAYSIA 

Population: 11,200,000. Voluntary military service. Total armed forces: 50,000. Estimated GNP 1970: \$3.95 billion. Defence budget 1971: Mal. $570 million ($US186,000,000). 3.06 Malaysian dollars= \$US1. 

### Army: 43,000.

7 infantry brigades, consisting of: 24 infantry battalions, 3 reconnaissance regiments. 3 artillery regiments. 1 Special Service unit. 3 signal regiments. Engineer and administrative units. Ferret scout cars; 105mm howitzers. RESERVES: About 50,000. Navy: 3,000. 2 ASW frigates (1 with Seacat SAM). 4 fast patrol boats (less than 100 tons). 24 other patrol boats (less than 100 tons). 6 coastal minesweepers. RESERVES: 600. 

### Air Force: 4,000; 30 combat aircraft. 

10 CA-27 Sabre fighter-bombers. 20 CL-41G Tebuan light training and strike aircraft. 8 Herald and 12 Caribou transports. 5 Dove, 2 HS-125 and 2 Heron liaison aircraft. 24 Alouette III and 10 S-61A helicopters. (1 squadron of Mirage III are on order.) 

## MONGOLIA 

Para-Military Forces: 50,000 - 14 bns field police.

Population: 1,315,000. Military service: 2 years. Total armed forces: 29,000. Estimated GNP 1970: \$0.63 billion. Estimated Defence expenditure 1971: 90 million tugrik (\$22,500,000). 4 tugrik = \$1. 

### Army: 28,000. 

2 infantry divisions. 40 T-34 and 100 T-54/55 med tanks; 10 SU-100 tank destroyers; 40 BTR-60 and 50 BTR-152 APC; 130mm guns and 152mm guns/howitzers. 

### Air Force: 1,000 men; no combat aircraft. 

Operates in support of the Army, and employs some Soviet technical advisers. 30 An-2, Il-14 and An-24 transports. Yak-11, Yak-18 and MiG-15 UTI trainers. 10 Mi-1 and Mi-4 helicopters. 1 SAM battalion with SA-2. Para-Military Forces: About 18,000 Security police. 

## NEW ZEALAND 

Population: 2,880,000. Voluntary military service (supplemented by selective national service of 14 weeks for the Army). Total armed forces: 12,750. Estimated GNP 1970: \$US5.77 billion. Defence budget 1971-72: $NZ110,450,000 ($US123,704,000). \$NZ 1 = \$US1.12. 

### Army: 5,600. 

1 infantry battalion. 1 artillery battery. Regular troops form the nucleus of a Combat Brigade Group, a Logistic Group and a Reserve Brigade Group. These units would be completed by the mobilization of Territorials. 10 M-41 It tanks; 9 Ferret scout cars; 40 M-113 APC; 28 105mm howitzers. DEPLOYMENT: 1 infantry bn (less one company) in Singapore. 1 infantry company in South Vietnam. RESERVES: 11,300 Territorials. 

### Navy: 2,900.

1 general purpose (GP) frigate with Seacat SAM (a second is due to be delivered in 1971). 2 ASW frigates with Seacat SAM. 50 2 escort minesweepers.

12 patrol craft (less than 100 tons). 2 Wasp hel (1 operates from the GP frigate).

RESERVES: 600 men, 5 patrol craft (less than 100 tons). 

### Air Force: 4,250; 27 combat aircraft.

1 fighter-bomber squadron with 10 A-4K and 4 TA-4K Skyhawk. 1 fighter-bomber squadron with 8 Vampire FB-5. 5 P-3B Orion maritime reconnaissance aircraft. 5 C-130 Devon and 9 Bristol Mark 31 med trans- ports. 14 Iroquois and 13 Sioux helicopters. DEPLOYMENT: 1 transport squadron in Singapore. 

## PAKISTAN

Population: 126,300,000. 2 years selective military service. Total armed forces: 392,000. Estimated GNP 1970: \$16 billion. Defence budget 1971-72: 3,400 million rupees (\$714,000,000). 4.76 rupees = \$1. 

### Army: 365,000 (including 25,000 Azad Kashmir troops). 

2 armoured divisions. 12 infantry divisions (2 more being raised). 1 independent armoured brigade. 1 air defence brigade. 100 M-47, 100 M-48, 100 T-54, 50 T-55 and 225 T-59 med tanks; 200 M-24, 75 M-41 and 20 PT-76 It tanks; 300 M-113 APC; about 900 25-pounder guns, 105mm and 155mm howitzers; 200 130mm guns; Cobra ATGW; 20 H-13 helicopters. 

### Navy: 10,000.

4 submarines. 1 light cruiser/training ship. 2 destroyers. 3 destroyer escorts. 2 fast frigates. 4 patrol boats. 8 coastal minesweepers. 2 small patrol boats (less than 100 tons). 2 UH-19 air-sea rescue helicopters.

### Air Force: 17,000; 285 combat aircraft.

1 light bomber squadron with II-28. 2 light bomber squadrons with B-57B. 2 fighter-bomber squadrons with Mirage IIIE. 8 fighter-bomber/interceptor squadrons with F-86. 4 interceptor squadrons with MiG-19. 1 interceptor squadron with 6 F-104A. 1 recce squadron with 4 RT-33A and 2 RB-57. (With the exceptions noted, combat squadrons have 16 aircraft). Transports include 8 C-130B and 1 F-27. 40 Sioux, Huskie, Alouette III and Mi-8 helicopters. Para-Military Forces: 280,000. 30,000 frontier corps; 250,000 militia. A new force is being raised - the East Pakistan Civil Armed Force. 

## PHILIPPINES

Population: 39,800,000. Selective military service. Total armed forces: 34,600. Estimated GNP 1970: \$5.9 billion. Defence budget 1971-72: 871 million pesos (\$135,500,000). 6.43 pesos = \$1. (Before 21 February 1970 - 3.9 pesos = \$1.) 

### Army: 17,600.

2 light infantry divisions (understrength). 2 infantry brigades. 15 engineer construction battalions. M-4 med tanks; M-24 and M-41 It tanks; M-113 APC. 

### Navy: 8,000 (including naval engineers).

1 destroyer escort. 4 coastal escorts. 7 patrol vessels. 47 patrol boats (less than 100 tons). 2 coastal minesweepers. 11 landing ships. 1 marine battalion. 5 engineer construction battalions. 

### Air Force: 9,000; 57 combat aircraft. 

20 F-5 fighter/ground-support aircraft. 8 T-28 ground support aircraft. 26 F-86F day-fighters. 3 T-33 armed trainers. Transports include 28 C-47 and 1 F-27. About 16 helicopters, incl UH-1H and H-34. Para-Military Forces: 23,500 Philippine Constabu- lary and about 400 armed civilian self-defence units. 

## SINGAPORE

Population: 2,100,000. Military service: 24-36 months. Total armed forces: 16,000. 51 Estimated GNP 1970: \$US1.82 billion. Defence budget 1971-72: S $484 million ($US158,170,000). 3.06 Singapore dollars= \$1. 

### Army: 14,000.

2 brigades, which include 1 armoured regiment, 6 infantry battalions, 1 artillery battalion, 1 engineer battalion, 1 signals battalion. (A third brigade is being formed.) 50 AMX-13 tanks; M-706 Commando APC; 25-pounder guns; 120mm mortars; 32 106mm recoilless rifles. RESERVES: 7,000, planned to increase to 9,000 by the end of 1971, 

### Navy: 500. 

1 seaward defence boat. 3 fast patrol boats (and 3 more on order). Air Force: 1,500; 36 combat aircraft. 1 GA sqn with 16 BAC-167 and 4 Hunter. I interceptor/recce sqn with 16 Hunter. 1 tpt/liaison sqn with 8 Cessna-172 and 2 Airtourer. 1 helicopter squadron with 4 Alouette III. 28 Bloodhound SAM launchers. Para-Military Forces: 2 police companies. 

## THAILAND 

Population: 35,000,000. Military service: 2 years. Total armed forces: 175,000. Estimated GNP 1970: \$6.1 billion. Defence budget 1970-71: 5,413,800,000 baht (\$260,300,000). 20.8 baht= \$1. 

### Army: 130,000.

4 infantry divisions (including 3 tank battalions). 1 regimental combat team. 1 SAM battery with HAWK. M-24 and M-41 It tanks; M-2 and M-16 armd half-tracks; M-8 armd cars; M3A1 scout cars; about 200 M-113 APC; 105mm and 155mm howitzers; 16 FH-1100 and 6 OH-23F hel. DEPLOYMENT: 11,250 in South Vietnam\$. 

### Navy: 21,500 (including 6,500 marines).

1 destroyer escort. 3 frigates (and 3 on order). 1 escort minesweeper. 17 submarine chasers.

4 coastal minesweepers. 2 coastal minelayers. 11 gunboats (1 less than 100 tons). 3 patrol gun boats. 8 landing ships. 8 landing craft. 1 maritime recce squadron with HU-16 and S-2. All due to be withdrawn by February 1972. 

### Air Force: 23,500; 144 combat aircraft.

11 F-5A and F-5B fighter-bombers. 20 F-86F day fighters. 2 RT-33A reconnaissance aircraft. 55 T-28D, 40 T-6 and 16 OV-10 COIN aircraft. 25 C-47 and 13 C-123B transports. About 60 hel, including 35 CH-34 and 23 UH-1H. 4 battalions of airfield defence troops. Para-Military Forces: 10,000 Volunteer Defence Corps; 8,000 Border Police. 

## VIETNAM-DEMOCRATIC REPUBLIC (NORTH) 

Population: 22,675,000. Military service: 3 years minimum. Total armed forces: 492,000. Estimated defence expenditure 1970: 2,150 million dong (\$584 million). 3.68 dong = \$1. 

### Army: 480,000.

14 infantry divisions. *1 artillery division (of 10 regiments). 2 armoured regiments. About 20 independent infantry regiments. 50 T-34 and 60 T-54 med tanks; 300 PT-76 It tanks; BTR-40 APC; SU-76 and JSU-122 SP guns; 75mm, 105mm, 122mm, 130mm and 152mm artillery; 57mm, 75mm, 82mm and 107mm recoilless rifles; 82mm, 100mm, 107mm, 120mm and 160mm mortars: 107mm, 122mm and 140mm RL; 6,000 37mm, 57mm, 85mm and 100mm AA guns. 35 SAM battalions (each with 6 SA-2 launchers). DEPLOYMENT: about 90,000 in South Vietnam, 75,000 in Laos and 40,000 in Cambodia. Navy: 3,000. 2 coastal escorts. 4 motor gunboats.* Infantry divisions normally total about 12,000 men including 3 infantry and 1 support regiment. =ex-Soviet. + =ex-Chinese. 52 About 24 motor gunboats (less than 100 tons). About 3 motor torpedo boats (less than 100 tons).\* About 12 small patrol boats (less than 100 tons). 

### Air Force: 9,000; 165 combat aircraft.

10 Il-28 light bombers.t 40 MiG-21F/PF interceptors with Atoll AAM.t 25 MiG-19 interceptors. 60- and 10\* MiG-17 interceptors. 10+ and 10\* MiG-15 interceptors. 8 An-2, 3 An-24, 10 Il-14 and 20 Li-2 transports. 20 Mi-4 and 2 Mi-6 helicopters. Para-Military Forces: 20,000 Frontier, Coast Security and People's Armed Security Forces; about 425,000 regional armed militia. 

## VIETNAM-REPUBLIC OF VIETNAM (SOUTH) 

Population: 18,800,000. Military service: 2 years minimum. Total armed forces: 500,000. Estimated GNP 1970: \$4.0 billion. Estimated defence expenditure 1971: 155,000 mil- lion piastres (\$564,000,000). 275 piastres = \$1 (before 4 Oct 1970, 117.5 = \$1). 

### Army: 414,000. 10 infantry divisions. 

1 airborne division (3 brigades). 6 independent armoured cavalry regiments. 3 independent infantry regiments. 18 ranger battalions. \* =ex-Chinese + =ex-Soviet. I With normally three regiments, each of 4 battalions, to an infantry division, there are some 150 infantry battalions in the regular army, but most units are below establishment; the actual strength of a battalion averages 500, and a regiment 2,000. 1 Special Forces Group. 35 artillery battalions. M-24, 200 M-41 and 40 AMX-13 It tanks; 250 Commando and Greyhound armd cars; M-3 scout cars; M-59 and M-113 APC; 105mm and 155mm SP guns. DEPLOYMENT: about 23,000 in Cambodia. 

### Navy: 31,000.

1 destroyer. 3 destroyer escorts. 6 patrol escorts. 2 patrol vessels. 3 coastal minesweepers. 70 fast patrol boats. 20 motor gunboats. 23 landing ships. About 200 landing craft. most less than About 600 river patrol boats 100 tons. About 350 motorized coastal defence junks. 

### Marine Corps: 15,000. 1 division. 

### Air Force: 40,000; 275 combat aircraft. 

1 tactical fighter squadron with F-5. 6 fighter-bomber squadrons with A-37. 3 fighter-bomber squadrons with Skyraider. Some RC-47 reconnaissance aircraft. 80 0-1 armed light aircraft. 20 AC-47 armed transport aircraft. (Combat squadrons have from 15-20 aircraft.) 25 C-47 and 25 C-119 transports. 35 Choctaw, 230 UH-1 and 10 CH-47 helicopters.  Para-Military Forces: 555,000. Regional Forces - 285,000, forming about 1,700 rifle companies, at the disposal of the provincial governors. Popular Forces - 250,000, a home guard of about 7,500 platoons, with light arms. Police Field Force - 20,000, including special internal security units with armd vehicles and helicopters. There is also a People's Self Defence Force of about 1,500,000.
