55 \# 1. ESTIMATES OF COMPARATIVE STRATEGIC STRENGTHS \## (A) Nuclear Strike Forces UNITED STATES AND SOVIET UNION

NOTE: Figures in brackets are approximate. 4 56 OTHER NATO AND WARSAW PACT COUNTRIES

(B) Growth of ICBM\|SLBM Strength, 1961-1971 (mid years)

a China is not included in this table. Her ability to deliver nuclear weapons appears to be limited to some Tu-16 and Tu-4 medium-range bombers, Il-28 short-range bombers and a few MRBM. b Including those in IRBM/MRBM fields. c In addition, there are about 300 Tu-16 Badgers in the Naval Air Force, configured for attacks on shipping, which could deliver nuclear weapons. d These aircraft are dual-capable and could have a non-nuclear role. e These became operational on 2 August 1971. f These missiles and aircraft are operated by a number of countries but may have non-nuclear roles. 57 \# 2. NUCLEAR DELIVERY VEHICLES 1971\* \## (A) Long and Medium Range MISSILES (USA)

## MISSILES (USSR)

AIRCRAFT (USA)

-   Listed by countries of origin. SAM and ASW missiles are not included. 58 AIRCRAFT (USSR)

## MISSILES (OTHER COUNTRIES)

## AIRCRAFT (OTHER COUNTRIES)

# (B) Short Range Missiles and Artillery

USA

## NOTES

a ICBM=inter-continental ballistic missile (range 4,000+miles) IRBM=intermediate-range ballistic missile (range 1,500-4,000 miles); IRBM=medium- range ballistic missile (range 500-1,500 miles); SRBM = short-range ballistic missile (range under 500 miles); SLBM=submarine-launched ballistic missile. b L=liquid; SL=storable liquid; S=solid; J=ram- or turbojet; HE = high explosive. c Operational range depends upon the payload carried; use of maximum payload may reduce range by up to 25 per cent below maximum. d MT = =megaton=1 tons of TNT equivalent (MT range= 1 MT or over); KT = kiloton=thousand tons of TNT equivalent (KT range= less than 1 MT). e The majority of Polaris A3 missiles, if not all, have been modified to carry three warheads of about 200 KT each. 1 Numerical designations for Soviet missiles (e.g. SS-9) are of US origin; names (e.g. Scarp) are of NATO origin. g SS-9 missiles have also been tested (i) with three war- heads of 4-5 MT each, (ii) with a modified payload for use as a depressed trajectory ICBM (DICBM) or frac- tional orbit bombardment system (FOBS). n A mobile IRBM (SS-XZ Scrooge) has been displayed and tested but is not known to be deployed opera- tionally. 1 A mobile solid-propellant missile (SS-14 Scapegoat), apparently with MRBM range, has been displayed and tested but is not known to be deployed operationally. I Launched only from the surface. k Possibly small propellant. I Long-range bomber=maximum range over 6,000 miles; medium-range bomber=maximum range 3,500- 6,000 miles, primarily designed for bombing missions. m Theoretical maximum range, with internal fuel only, at optimum altitude and speed. Ranges for strike air- craft assume no weapon load. Especially in the case of strike aircraft, therefore, range falls sharply for flights at lower altitude, at higher speed or with full weapons load (e.g. combat radius of A-7, at operational height and speed, with typical weapons load, is approximately 620 miles). 12 Mach 1 (M=1.0)=speed of sound. o ASM=air-to-surface missile. P F-104 are no longer in active service as strike aircraft with the US Air Force but remain in service with other NATO air forces. a Names of Soviet aircraft (e.g. Bear) are of NATO origin. r Naval Air Force versions of the Tu-16 carry 2x Kelt or 2x Kennel ASM for anti-shipping use. 60 \## 3. DEFENCE EXPENDITURE AND NATIONAL ECONOMIES

t Excluding financial assistance to West Berlin which included would make the entry read: 7,067 6,860 4.7 119 4.2 4.2 3.8 61 3. DEFENCE EXPENDITURE AND NATIONAL ECONOMIES-continued

-   Column 1 represents the estimated out-turn of defence expenditure in 1970. Column 2 represents planned defence expenditure for the current year, in most cases according to the budget statements of national governments. \*\* The GNP figures are estimated at current market prices and the percentages may differ from those published by national governments and international organizations. The valuation of the Soviet GNP and the rate of exchange used for the defence expenditure were ex- plained in The Military Balance 1970-1971, pp. 10-11. n.a. = not available. \# 4. COMPARATIVE DEFENCE EXPENDITURE, GROSS NATIONAL PRODUCT AND MANPOWER FIGURES 1951-1970 Defence Expenditure (in \$ million)a

a Exchange rates used are the same as in the GNP table below except for the USSR, which are calculated on the basis used in the country section (pp. 5-7) and explained in The Military Balance 1970-1971, pp. 10-12. b NATO definition of defence expenditure has been used. Gross National Product AT CURRENT MARKET PRICES AND EXCHANGE RATES (\$ billion)

a Net Material Product converted at a constant exchange rate of 0.9 roubles = \$1. The UN accounts definition has been used. This consists of: individual and collective consumption, net fixed capital formation, and net exports of goods and productive services. \## Total Armed Forces (in thousands)

a National Police Reserve. b Security Force. c Self Defence Forces. d Excluding forces enlisted outside Britain. \# 5. TANK CHARACTERISTICS

ยง Excluding China, which makes a copy of the Soviet T-54 known as the T-59 and a light tank, the T-62. \* A number have been rebuilt with 152mm combined gun and Shillelagh missile launcher and are designated M-60 A1 E1 and E2: neither of these versions is operational. \*\* Also manufactured in Britain. t Combined gun and Shillelagh missile launcher. \# 6. OVERSEAS DEPLOYMENT OF FORCES\* (A) AFRICA - SOUTH OF THE SAHARA

-   Excluding Europe, all forces stationed in colonies or metropolitan territories, and small contingents such as military advisory groups, training teams, seconded personnel and United Nations observer teams. a A CF Regt (RIAOM) is a regimental group containing infantry and armour with supporting services. b On the Beira patrol. Frigates on this patrol are found from ships based in United Kingdom or Singapore.

(B) MIDDLE EAST AND MEDITERRANEAN

c There is a United Nations peace-keeping force in Cyprus (UNFICYP), military personnel strength about 2,950, with contingents from Austria, Britain, Canada, Denmark, Finland, Ireland and Sweden and 175 civilian police from Australia, Austria, Denmark and Sweden. d Britain has a DDG and 2 frigates stationed in the Mediterranean, reinforced from time to time by other ships. These are normally based in Malta. . British forces are to be withdrawn by the end of 1971. (c) EAST ASIA

(D) LATIN AMERICA

f The United States has substantial naval forces in the Pacific, based in a number of countries. (E) REST OF ASIA

, = After 1971. Under Five-Power defence arrangements taking effect from 1 November 1971 (see p. 43) Britain is to keep five frigates or destroyers on station East of Suez, including Hong Kong. Australia is to provide a submarine in the Singapore area for most of the time. A Less a detachment in Singapore. 1 15-20,000 in Laos and North Vietnam. I In May: the figure is to be reduced to 6,000 by November 1971. k Mid-June. \# 7. MAJOR IDENTIFIED ARMS AGREEMENTS, JULY 1970-JUNE 1971 (A) WESTERN EUROPE

n.a. = not available. a Another 600 are to be built under licence in Italy.

b France has since banned deliveries and the United States is holding action on these deals in abeyance. n.a. = not available. c Cost of leasing for 4 years.

(F) AFRICA - SOUTH OF THE SAHARA

(G) NORTH AMERICA

n.a. = not available. NOTES may include sub-contractors in the purchasing country, as well as prime contractors in the supplying country. No licensing agreements are included. American, Soviet and Chinese military aid to Vietnam, Cambodia, Laos and Korea, and Soviet deliveries to members of the Warsaw Pact are excluded. This table lists major agreements on a firm-to- government and on a government-to-government basis, and covers both credit and cash sales. Costs to recipients may include spares, support, etc., and reflect the value of goods taken in part-exchange where applicable. Payees 8. SECONDARY ARMS' PRODUCERS\*

NOTES \* Countries other than the United States, the Soviet Union, Britain and France which are considered to be primary producers. t SS = Supersonic. P= Arms of producer country's own design. L = Arms produced or assembled, not of own design. Most aircraft come in this category because the engines are licensed. a All fighter, bomber or COIN aircraft except where indicated. b Includes ASW missiles. Includes MCM and landing ships. d Includes landing craft. Includes armoured car, scout car and APC. / Includes Tu-16 medium bomber. g Includes Japanese designed MR aircraft.
