# PREFACE

The Military Balance introduces this year much new, material. There are tables which give comparative figures for the last 20 years for the armed forces, defence expenditure and Gross National Product of major countries. The characteristics of the world's tanks are set out. Included as part of the European balance is a comparison of the new ship deliveries to the NATO and Warsaw Pact navies between 1961-70. There is a special section showing forces outside their parent country and the countries in which they are stationed. Other new features are tables of short-range nuclear delivery vehicles and of arms produc- tion in countries with significant and growing, but not all-embracing, defence industries. Certain items have been omitted, to save space or because last year's entries remain essentially up to date. The Latin American countries are a case in point: they have been excluded this time but it is the intention to return to them next year. An index is included (see p. 83) to give guidance to features appearing in one or more, but not all, of the last four issues (including this one). The Institute assumes full responsibility for the facts and judgments which the document contains. The co-operation of governments has been sought and in many cases received. Not all countries have been equally co-operative in producing information and some figures have been estimated. The Institute owes a considerable debt to a number of its own members and consultants who have assisted in compiling and checking material. Manpower figures given are those of regular forces, although an indication of the size of para-military forces, militia or reserve forces has been given in the sections dealing with individual countries. Figures for defence expenditures are the latest available and are generally exclusive of military aid. A glossary of the abbreviations that have been used in the text will be found overleaf. On the facing page are notes explaining the bases for the conversion of national currency figures into dollars and giving the strengths of some military formations. This study examines the facts of military power as they existed in July 1971. No projections of force levels or weapons beyond 1971 have been included, except where explicitly stated. The material should not be regarded as a comprehensive guide to the balance of strategic power; in particular it does not reflect the facts of geography, vulnerability or efficiency, except where these are touched upon in the appendix on the NATO-Warsaw Pact balance. The Military Balance is complemented by another annual publication, Strategic Survey, published each spring, which reviews the most significant issues of international security and conflict in the previous calendar year and describes the major developments in strategic and defence policy and in weapons throughout the world. 

September 1971
